In [1]:
import tradingeconomics as te

In [2]:
te.login()

'You are logged in as a guest:guest'

# Comtrade

##### Get detailed information about Comtrade categories
/comtrade/categories
https://api.tradingeconomics.com/comtrade/categories?c=guest:guest

In [3]:
te.getCmtCategories(output_type='df')

,id,name,parentId,pretty_name
0,01,Live animals,a1,Live animals
1,0101,"Horses, asses, mules and hinnies, live",01,"Horses, asses, mules and hinnies, live"
2,0102,"Bovine animals, live",01,"Bovine animals, live"
3,0103,"Swine, live",01,"Swine, live"
4,0104,"Sheep and goats, live",01,"Sheep and goats, live"
5,0105,"Chickens, ducks, geese, turkeys, and guineas, ...",01,"Chickens, ducks, geese, turkeys, and guineas, ..."
6,0106,Other live animals,01,"Animals, live, not specified elsewhere"
7,02,Meat & edible meat offal,a1,Meat and edible meat offal
8,0201,"Meat of bovine animals, fresh or chilled",02,"Meat of bovine animals, fresh or chilled"
9,0202,"Meat of bovine animals, frozen",02,"Meat of bovine animals, frozen"

##### Get total Imports by main category
/comtrade/import/{country}
https://api.tradingeconomics.com/comtrade/import/india?c=guest:guest

In [4]:
te.getCmtCountryByCategory(country = 'india', type = 'import',  output_type = 'df' )

,symbol,country,value,date,type,category,url,title,lastupdate
0,INDWLDXX271,India,104358496964,2020,Import,"Mineral fuels, oils, distillation products",/india/imports/mineral-fuels-oils-distillation...,"India Imports of Mineral fuels, oils, distilla...",2021-05-20T20:51:00
1,INDWLDXX851,India,42944414157,2020,Import,"Electrical, electronic equipment",/india/imports/electrical-electronic-equipment,"India Imports of Electrical, electronic equipment",2021-05-20T20:51:00
2,INDWLDXX711,India,41049740675,2020,Import,"Pearls, precious stones, metals, coins",/india/imports/pearls-precious-stones-metals-c...,"India Imports of Pearls, precious stones, meta...",2021-05-20T20:51:00
3,INDWLDXX841,India,35201384349,2020,Import,"Machinery, nuclear reactors, boilers",/india/imports/nuclear-reactors-boilers-machinery,"India Imports of Machinery, nuclear reactors, ...",2021-05-20T20:51:00
4,INDWLDXX291,India,18154638691,2020,Import,Organic chemicals,/india/imports/organic-chemicals,India Imports of Organic chemicals,2021-05-20T20:51:00
5,INDWLDXX391,India,11974523771,2020,Import,Plastics,/india/imports/plastics,India Imports of Plastics,2021-05-20T20:51:00
6,INDWLDXX151,India,10597474056,2020,Import,"Animal, vegetable fats and oils, cleavage prod...",/india/imports/animal-vegetable-fats-oils-clea...,"India Imports of Animal, vegetable fats and oi...",2021-05-20T20:51:00
7,INDWLDXX901,India,8218099642,2020,Import,"Optical, photo, technical, medical apparatus",/india/imports/optical-photo-technical-medical...,"India Imports of Optical, photo, technical, me...",2021-05-20T20:51:00
8,INDWLDXX721,India,7550873600,2020,Import,Iron and steel,/india/imports/iron-steel,India Imports of Iron and steel,2021-05-20T20:51:00
9,INDWLDXX311,India,7177367513,2020,Import,Fertilizers,/india/imports/fertilizers,India Imports of Fertilizers,2021-05-20T20:51:00

##### Total Exports by main category
/comtrade/export/{country}
https://api.tradingeconomics.com/comtrade/export/united%20states?c=guest:guest

In [5]:
te.getCmtCountryByCategory(country = 'united states', type = 'export',  output_type = 'df' )

,symbol,country,value,date,type,category,url,title,lastupdate
0,USAWLDXX842,United States,182585530775,2020,Export,"Machinery, nuclear reactors, boilers",/united-states/exports/nuclear-reactors-boiler...,"United States exports of machinery, nuclear re...",2021-05-18T09:16:00
1,USAWLDXX852,United States,162884379108,2020,Export,"Electrical, electronic equipment",/united-states/exports/electrical-electronic-e...,"United States exports of electrical, electroni...",2021-05-18T09:16:00
2,USAWLDXX272,United States,155092241024,2020,Export,"Mineral fuels, oils, distillation products",/united-states/exports/mineral-fuels-oils-dist...,"United States exports of mineral fuels, oils, ...",2021-05-18T09:16:00
3,USAWLDXX872,United States,105158056180,2020,Export,"Vehicles other than railway, tramway",/united-states/exports/vehicles-not-railway-tr...,United States exports of vehicles other than r...,2021-05-18T09:16:00
4,USAWLDXX902,United States,83404371523,2020,Export,"Optical, photo, technical, medical apparatus",/united-states/exports/optical-photo-technical...,"United States exports of optical, photo, techn...",2021-05-18T09:16:00
5,USAWLDXX882,United States,80936266187,2020,Export,"Aircraft, spacecraft",/united-states/exports/aircraft-spacecraft,"United States exports of aircraft, spacecraft",2021-05-18T09:16:00
6,USAWLDXX392,United States,60216190079,2020,Export,Plastics,/united-states/exports/plastics,United States exports of plastics,2021-05-18T09:16:00
7,USAWLDXX712,United States,58810543095,2020,Export,"Pearls, precious stones, metals, coins",/united-states/exports/pearls-precious-stones-...,"United States exports of pearls, precious ston...",2021-05-18T09:16:00
8,USAWLDXX302,United States,53938940706,2020,Export,Pharmaceutical products,/united-states/exports/pharmaceutical-products,United States exports of pharmaceutical products,2021-05-18T09:16:00
9,USAWLDXX992,United States,42911776265,2020,Export,Commodities not specified according to kind,/united-states/exports/commodities-not-specifi...,United States exports of commodities not speci...,2021-05-18T09:16:00

##### Imports by specific category
/comtrade/import/{country}/{category}
https://api.tradingeconomics.com/comtrade/import/united%20kingdom/Coffee,%20tea,%20mate%20and%20spices?c=guest:guest

In [6]:
te.getCmtCountryByCategory(country = 'united kingdom', type = 'import', category = 'Coffee, tea, mate and spices', output_type = 'df' )

,symbol,country1,country2,value,date,type,category,url,title,lastupdate
0,GBRWLDXX091,United Kingdom,World,1721542765,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/coffee-tea-mate-spices,"United Kingdom Imports of Coffee, tea, mate an...",2021-05-20T01:57:00
1,GBRFRAXX091,United Kingdom,France,220219959,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/france/coffee-tea-mate...,"United Kingdom Imports from France of Coffee, ...",2021-05-20T02:24:00
2,GBRDEUXX091,United Kingdom,Germany,174316040,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/germany/coffee-tea-mat...,"United Kingdom Imports from Germany of Coffee,...",2021-05-20T02:24:00
3,GBRKENXX091,United Kingdom,Kenya,169022671,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/kenya/coffee-tea-mate-...,"United Kingdom Imports from Kenya of Coffee, t...",2021-05-20T02:26:00
4,GBRINDXX091,United Kingdom,India,121968550,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/india/coffee-tea-mate-...,"United Kingdom Imports from India of Coffee, t...",2021-05-20T02:25:00
5,GBRVNMXX091,United Kingdom,Vietnam,121566825,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/vietnam/coffee-tea-mat...,"United Kingdom Imports from Vietnam of Coffee,...",2021-05-20T02:56:00
6,GBRESPXX091,United Kingdom,Spain,108184741,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/spain/coffee-tea-mate-...,"United Kingdom Imports from Spain of Coffee, t...",2021-05-20T02:54:00
7,GBRBRAXX091,United Kingdom,Brazil,99625041,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/brazil/coffee-tea-mate...,"United Kingdom Imports from Brazil of Coffee, ...",2021-05-20T01:59:00
8,GBRCHNXX091,United Kingdom,China,70418049,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/china/coffee-tea-mate-...,"United Kingdom Imports from China of Coffee, t...",2021-05-20T02:00:00
9,GBRITAXX091,United Kingdom,Italy,69897467,2020,Import,"Coffee, tea, mate and spices",/united-kingdom/imports/italy/coffee-tea-mate-...,"United Kingdom Imports from Italy of Coffee, t...",2021-05-20T02:26:00

##### Exports by specific category
/comtrade/export/{country}/{category}
https://api.tradingeconomics.com/comtrade/export/india/live%20animals?c=guest:guest

In [7]:
te.getCmtCountryByCategory(country = 'india', type = 'export', category = 'live animals', output_type = 'df' )

,symbol,country1,country2,value,date,type,category,url,title,lastupdate
0,INDWLDXX012,India,World,5349619,2020,Export,Live animals,/india/exports/live-animals,India exports of live animals,2021-05-20T20:51:00
1,INDAREXX012,India,United Arab Emirates,4926065,2020,Export,Live animals,/india/exports/united-arab-emirates/live-animals,India exports of live animals to United Arab E...,2021-05-20T21:48:00
2,INDNPLXX012,India,Nepal,107033,2020,Export,Live animals,/india/exports/nepal/live-animals,India exports of live animals to Nepal,2021-05-20T21:22:00
3,INDBTNXX012,India,Bhutan,86738,2020,Export,Live animals,/india/exports/bhutan/live-animals,India exports of live animals to Bhutan,2021-05-20T20:53:00
4,INDKENXX012,India,Kenya,82079,2020,Export,Live animals,/india/exports/kenya/live-animals,India exports of live animals to Kenya,2021-05-20T21:20:00
5,INDBGDXX012,India,Bangladesh,61819,2020,Export,Live animals,/india/exports/bangladesh/live-animals,India exports of live animals to Bangladesh,2021-05-20T20:52:00
6,INDUGAXX012,India,Uganda,53187,2020,Export,Live animals,/india/exports/uganda/live-animals,India exports of live animals to Uganda,2021-05-20T21:48:00
7,INDVNMXX012,India,Vietnam,12223,2020,Export,Live animals,/india/exports/vietnam/live-animals,India exports of live animals to Vietnam,2021-05-20T21:48:00
8,INDTHAXX012,India,Thailand,11476,2020,Export,Live animals,/india/exports/thailand/live-animals,India exports of live animals to Thailand,2021-05-20T21:47:00
9,INDTZAXX012,India,Tanzania,5800,2020,Export,Live animals,/india/exports/tanzania/live-animals,India exports of live animals to Tanzania,2021-05-20T21:48:00

##### Get detailed information about Comtrade countries
/comtrade/countries
https://api.tradingeconomics.com/comtrade/countries?c=guest:guest

In [8]:
te.getCmtCountry(output_type='df')

      id                    name    region           subregion  iso  year
0      0                   World      None                None  WLD  None
1     10              Antarctica      None                None  ATA  2015
2    100                Bulgaria    Europe      Eastern Europe  BGR  2019
3    104                 Myanmar      Asia  South-Eastern Asia  MMR  2020
4    108                 Burundi    Africa      Western Africa  BDI  2019
..   ...                     ...       ...                 ...  ...   ...
285   90         Solomon Islands   Oceania           Melanesia  SLB  2018
286   92  British Virgin Islands  Americas           Caribbean  VGB  2015
287   96                  Brunei      Asia  South-Eastern Asia  BRN  2019
288   97          European Union    Europe               EU-28  EU2  2020
289  all                     All       all                 all  all  2015

[290 rows x 6 columns]

##### Snapshot of data per country
/comtrade/country/{country}
https://api.tradingeconomics.com/comtrade/country/portugal?c=guest:guest

In [9]:
te.getCmtCountry(country = 'portugal' , output_type = 'df')

,symbol,country1,country2,type,category,url,title,lastupdate
0,PRTAUS84322,Portugal,Australia,Export,Agricultural for Soil Preparation,/portugal/exports/australia/agricultural-machi...,Portugal exports of agricultural for soil prep...,2021-08-24T14:37:00
1,PRTAND00002,Portugal,Andorra,Export,None,/portugal/exports/andorra,Portugal exports to Andorra,2021-08-26T11:43:00
2,PRTZAF45042,Portugal,South Africa,Export,Agglomerated cork,/portugal/exports/south-africa/agglomerated-cork,Portugal exports of agglomerated cork to South...,2021-08-24T16:12:00
3,PRTALB00002,Portugal,Albania,Export,None,/portugal/exports/albania,Portugal exports to Albania,2021-08-26T11:43:00
4,PRTVNM45042,Portugal,Vietnam,Export,Agglomerated cork,/portugal/exports/vietnam/agglomerated-cork,Portugal exports of agglomerated cork to Vietnam,2021-08-27T10:35:00
5,PRTAGO00002,Portugal,Angola,Export,None,/portugal/exports/angola,Portugal exports to Angola,2021-08-26T11:43:00
6,PRTVEN45042,Portugal,Venezuela,Export,Agglomerated cork,/portugal/exports/venezuela/agglomerated-cork,Portugal exports of agglomerated cork to Venez...,2021-08-24T16:24:00
7,PRTAFG00002,Portugal,Afghanistan,Export,None,/portugal/exports/afghanistan,Portugal exports to Afghanistan,2021-08-26T11:43:00
8,PRTUZB45042,Portugal,Uzbekistan,Export,Agglomerated cork,/portugal/exports/uzbekistan/agglomerated-cork,Portugal exports of agglomerated cork to Uzbek...,2021-08-24T16:23:00
9,PRTABW00002,Portugal,Aruba,Export,None,/portugal/exports/aruba,Portugal exports to Aruba,2021-08-26T11:43:00

##### Snapshot of data per country filtered by type: import or export
/comtrade/country/{country}?type={type}
https://api.tradingeconomics.com/comtrade/country/portugal?type=export&c=guest:guest

In [19]:
te.getCmtCountryFilterByType(country1 = 'portugal', type = 'export', output_type='df')

,symbol,country1,country2,value,date,type,category,url,title,lastupdate
0,PRTWLD00002,Portugal,World,61524484005,2020,Export,None,/portugal/exports,Portugal exports,2021-08-26T11:43:00
1,PRTESP00002,Portugal,Spain,15625642345,2020,Export,None,/portugal/exports/spain,Portugal exports to Spain,2021-08-26T11:43:00
2,PRTWLDXX872,Portugal,World,8558325383,2020,Export,"Vehicles other than railway, tramway",/portugal/exports/vehicles-not-railway-tramway,Portugal exports of vehicles other than railwa...,2021-08-26T08:08:00
3,PRTFRA00002,Portugal,France,8317382525,2020,Export,None,/portugal/exports/france,Portugal exports to France,2021-08-26T11:43:00
4,PRTDEU00002,Portugal,Germany,7289169272,2020,Export,None,/portugal/exports/germany,Portugal exports to Germany,2021-08-26T11:43:00
5,PRTWLDXX852,Portugal,World,5029294651,2020,Export,"Electrical, electronic equipment",/portugal/exports/electrical-electronic-equipment,"Portugal exports of electrical, electronic equ...",2021-08-26T08:08:00
6,PRTWLDXX842,Portugal,World,4019337516,2020,Export,"Machinery, nuclear reactors, boilers",/portugal/exports/nuclear-reactors-boilers-mac...,"Portugal exports of machinery, nuclear reactor...",2021-08-26T08:08:00
7,PRTGBR00002,Portugal,United Kingdom,3505176016,2020,Export,None,/portugal/exports/united-kingdom,Portugal exports to United Kingdom,2021-08-26T11:43:00
8,PRTWLDXX392,Portugal,World,3154015977,2020,Export,Plastics,/portugal/exports/plastics,Portugal exports of plastics,2021-08-26T08:08:00
9,PRTUSA00002,Portugal,United States,3054482866,2020,Export,None,/portugal/exports/united-states,Portugal exports to United States,2021-08-26T11:43:00

##### Snapshot of trade between two countries
/comtrade/country/{country_1}/{country_2}
https://api.tradingeconomics.com/comtrade/country/portugal/spain?c=guest:guest

In [12]:
te.getCmtTwoCountries(country1 = 'portugal', country2 = 'spain', output_type = 'df')

,symbol,country1,country2,type,category,url,title
0,PRTESP00001,Portugal,Spain,Import,None,/portugal/imports/spain,Portugal imports from Spain
1,PRTESP00002,Portugal,Spain,Export,None,/portugal/exports/spain,Portugal exports to Spain
2,PRTESPXX871,Portugal,Spain,Import,"Vehicles other than railway, tramway",/portugal/imports/spain/vehicles-not-railway-t...,Portugal Imports from Spain of Vehicles other ...
3,PRTESPXX872,Portugal,Spain,Export,"Vehicles other than railway, tramway",/portugal/exports/spain/vehicles-not-railway-t...,Portugal exports of vehicles other than railwa...
4,PRTESPXX841,Portugal,Spain,Import,"Machinery, nuclear reactors, boilers",/portugal/imports/spain/nuclear-reactors-boile...,"Portugal Imports from Spain of Machinery, nucl..."
5,PRTESPXX851,Portugal,Spain,Import,"Electrical, electronic equipment",/portugal/imports/spain/electrical-electronic-...,"Portugal Imports from Spain of Electrical, ele..."
6,PRTESP87082,Portugal,Spain,Export,Parts and Accessories of the Motor Vehicles,/portugal/exports/spain/parts-accessories-moto...,Portugal exports of parts and accessories of t...
7,PRTESPXX391,Portugal,Spain,Import,Plastics,/portugal/imports/spain/plastics,Portugal Imports from Spain of Plastics
8,PRTESP87081,Portugal,Spain,Import,Parts and Accessories of the Motor Vehicles,/portugal/imports/spain/parts-accessories-moto...,Portugal Imports from Spain of Parts and Acces...
9,PRTESPXX392,Portugal,Spain,Export,Plastics,/portugal/exports/spain/plastics,Portugal exports of plastics to Spain

##### Snapshot of trade between two countries filtered by type: import or export
/comtrade/country/{country_1}/{country_2}?type={type}
https://api.tradingeconomics.com/comtrade/country/portugal/spain?type=import&c=guest:guest

In [15]:
te.getCmtCountryFilterByType(country1='portugal', country2='spain',type='import', output_type='df')

,symbol,country1,country2,value,date,type,category,url,title,lastupdate
0,PRTESP00001,Portugal,Spain,25325634333,2020,Import,None,/portugal/imports/spain,Portugal imports from Spain,2021-08-26T11:43:00
1,PRTESPXX871,Portugal,Spain,2681798058,2020,Import,"Vehicles other than railway, tramway",/portugal/imports/spain/vehicles-not-railway-t...,Portugal Imports from Spain of Vehicles other ...,2021-08-26T09:26:00
2,PRTESPXX841,Portugal,Spain,1887802495,2020,Import,"Machinery, nuclear reactors, boilers",/portugal/imports/spain/nuclear-reactors-boile...,"Portugal Imports from Spain of Machinery, nucl...",2021-08-26T09:26:00
3,PRTESPXX851,Portugal,Spain,1806612034,2020,Import,"Electrical, electronic equipment",/portugal/imports/spain/electrical-electronic-...,"Portugal Imports from Spain of Electrical, ele...",2021-08-26T09:26:00
4,PRTESPXX391,Portugal,Spain,1425608935,2020,Import,Plastics,/portugal/imports/spain/plastics,Portugal Imports from Spain of Plastics,2021-08-26T09:26:00
5,PRTESP87081,Portugal,Spain,1165860372,2020,Import,Parts and Accessories of the Motor Vehicles,/portugal/imports/spain/parts-accessories-moto...,Portugal Imports from Spain of Parts and Acces...,2021-08-24T16:13:00
6,PRTESPXX271,Portugal,Spain,1119371526,2020,Import,"Mineral fuels, oils, distillation products",/portugal/imports/spain/mineral-fuels-oils-dis...,"Portugal Imports from Spain of Mineral fuels, ...",2021-08-26T09:26:00
7,PRTESP87031,Portugal,Spain,1058670956,2020,Import,Motor cars and vehicles for transporting persons,/portugal/imports/spain/motor-cars-vehicles-tr...,Portugal Imports from Spain of Motor cars and ...,2021-08-24T16:13:00
8,PRTESPXX021,Portugal,Spain,784008717,2020,Import,Meat and edible meat offal,/portugal/imports/spain/meat-edible-meat-offal,Portugal Imports from Spain of Meat and edible...,2021-08-26T09:26:00
9,PRTESPXX721,Portugal,Spain,757258594,2020,Import,Iron and steel,/portugal/imports/spain/iron-steel,Portugal Imports from Spain of Iron and steel,2021-08-26T09:26:00

##### Total Imports by country
/comtrade/import/{country}/totals
https://api.tradingeconomics.com/comtrade/import/united%20states/totals?c=guest:guest

In [17]:
te.getTotalByType(country = 'united states', type = 'import', output_type = 'df' )

,symbol,country1,country2,value,date,type,category,url,title,lastupdate
0,USAWLD00001,United States,World,2405381557667,2020,Import,None,/united-states/imports,United States imports,2021-04-28T16:51:00
1,USACHN00001,United States,China,457164215509,2020,Import,None,/united-states/imports/china,United States imports from China,2021-04-28T16:51:00
2,USAMEX00001,United States,Mexico,328861803529,2020,Import,None,/united-states/imports/mexico,United States imports from Mexico,2021-04-28T16:51:00
3,USACAN00001,United States,Canada,276195545882,2020,Import,None,/united-states/imports/canada,United States imports from Canada,2021-04-28T16:51:00
4,USAJPN00001,United States,Japan,122483985438,2020,Import,None,/united-states/imports/japan,United States imports from Japan,2021-04-28T16:51:00
5,USADEU00001,United States,Germany,117393017842,2020,Import,None,/united-states/imports/germany,United States imports from Germany,2021-04-28T16:51:00
6,USAVNM00001,United States,Vietnam,83211920317,2020,Import,None,/united-states/imports/vietnam,United States imports from Vietnam,2021-04-28T16:51:00
7,USAKOR00001,United States,South Korea,78292069677,2020,Import,None,/united-states/imports/south-korea,United States imports from South Korea,2021-04-28T16:51:00
8,USACHE00001,United States,Switzerland,75504461806,2020,Import,None,/united-states/imports/switzerland,United States imports from Switzerland,2021-04-28T16:51:00
9,USAIRL00001,United States,Ireland,65779092043,2020,Import,None,/united-states/imports/ireland,United States imports from Ireland,2021-04-28T16:51:00

##### Total Exports by country
/comtrade/export/{country}/totals
https://api.tradingeconomics.com/comtrade/export/india/totals?c=guest:guest

In [20]:
te.getTotalByType(country='india', type='export', output_type='df')

,symbol,country1,country2,value,date,type,category,url,title,lastupdate
0,INDWLD00002,India,World,275488744927,2020,Export,None,/india/exports,India exports,2021-03-30T00:37:00
1,INDUSA00002,India,United States,49320596192,2020,Export,None,/india/exports/united-states,India exports to United States,2021-03-30T00:37:00
2,INDCHN00002,India,China,19008266739,2020,Export,None,/india/exports/china,India exports to China,2021-03-30T00:37:00
3,INDARE00002,India,United Arab Emirates,17953335407,2020,Export,None,/india/exports/united-arab-emirates,India exports to United Arab Emirates,2021-03-30T00:37:00
4,INDHKG00002,India,Hong Kong,9537368599,2020,Export,None,/india/exports/hong-kong,India exports to Hong Kong,2021-03-30T00:37:00
5,INDSGP00002,India,Singapore,8295020166,2020,Export,None,/india/exports/singapore,India exports to Singapore,2021-03-30T00:37:00
6,INDBGD00002,India,Bangladesh,7912820545,2020,Export,None,/india/exports/bangladesh,India exports to Bangladesh,2021-03-30T00:37:00
7,INDGBR00002,India,United Kingdom,7767619502,2020,Export,None,/india/exports/united-kingdom,India exports to United Kingdom,2021-03-30T00:37:00
8,INDDEU00002,India,Germany,7656984753,2020,Export,None,/india/exports/germany,India exports to Germany,2021-03-30T00:37:00
9,INDNLD00002,India,Netherlands,6261190370,2020,Export,None,/india/exports/netherlands,India exports to Netherlands,2021-03-30T00:37:00

##### Historical data
/comtrade/historical/{symbol}
https://api.tradingeconomics.com/comtrade/historical/PRTESP24031?c=guest:guest

In [21]:
te.getCmtHistorical(symbol='PRTESP24031', output_type='df')

         symbol                 date      value
0   PRTESP24031  1997-12-31T00:00:00      707.0
1   PRTESP24031  1998-12-31T00:00:00     7020.0
2   PRTESP24031  2000-12-31T00:00:00    54310.0
3   PRTESP24031  2002-12-31T00:00:00    89710.0
4   PRTESP24031  2003-12-31T00:00:00     5290.0
5   PRTESP24031  2004-12-31T00:00:00     8792.0
6   PRTESP24031  2005-12-31T00:00:00     5730.0
7   PRTESP24031  2006-12-31T00:00:00   294690.0
8   PRTESP24031  2007-12-31T00:00:00   340640.0
9   PRTESP24031  2008-12-31T00:00:00   156900.0
10  PRTESP24031  2009-12-31T00:00:00    22385.0
11  PRTESP24031  2010-12-31T00:00:00   184210.0
12  PRTESP24031  2011-12-31T00:00:00     4520.0
13  PRTESP24031  2012-12-31T00:00:00   640320.0
14  PRTESP24031  2014-12-31T00:00:00    60868.0
15  PRTESP24031  2015-12-31T00:00:00      809.0
16  PRTESP24031  2016-12-31T00:00:00    11361.0
17  PRTESP24031  2017-12-31T00:00:00    12977.0
18  PRTESP24031  2018-12-31T00:00:00     4018.0
19  PRTESP24031  2019-12-31T00:00:00  3479548.0
20  PRTESP24031  2020-12-31T00:00:00   114349.0