In [1]:
import tradingeconomics as te
te.login()

'You are logged in as a guest:guest'

# Indicators

##### 1 List of all indicators
/indicators

https://api.tradingeconomics.com/indicators?c=guest:guest

In [2]:
te.getIndicatorData(output_type='df')

Without country indication only a list of available indicators will be returned...

             Category CategoryGroup
0  1 Month Bill Yield       Markets
1   2 Year Note Yield       Markets
2  20 Year bond Yield       Markets
3  3 Month Bill Yield       Markets
4   3 Year Note Yield       Markets
5  30 Year bond-Yield       Markets
6   5 Year Note Yield       Markets
7  52 Week Bill Yield       Markets
8  6 Month Bill Yield       Markets
9   7 Year Note Yield       Markets

##### 2 List of indicators by country
/country/{country}

https://api.tradingeconomics.com/country/united%20states?c=guest:guest

In [5]:
te.getIndicatorData(country='united states', output_type='df')

,Country,Category,Title,LatestValue,LatestValueDate,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,United States,20 Year bond Yield,United States 20 Year bond Yield,2.00,2021-09-13T00:00:00,,%,/united-states/20-year-bond-yield,Markets,,Daily,USGG20Y,2021-08-25T17:51:00,2.02,2021-09-10T00:00:00
1,United States,ADP Employment Change,United States ADP Employment Change,374.00,2021-08-31T00:00:00,"Automatic Data Processing, Inc.",Thousand,/united-states/adp-employment-change,Labour,SA,Monthly,UNITEDSTAADPEMPCHA,2014-04-30T13:57:00,326.00,2021-07-31T00:00:00
2,United States,API Crude Imports,United States API Crude Imports,-0.27,2021-08-27T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-crude-imports,Business,,Weekly,UNITEDSTAAPICRUIMP,2020-07-20T10:54:00,-0.27,2021-08-20T00:00:00
3,United States,API Crude Oil Stock Change,United States API Crude Oil Stock Change,-2.88,2021-09-03T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-crude-oil-stock-change,Business,,Weekly,APICRUDEOIL,2017-11-28T15:21:00,-4.05,2021-08-27T00:00:00
4,United States,API Crude Runs,United States API Crude Runs,-1.22,2021-09-03T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-crude-runs,Business,,Weekly,UNITEDSTAAPICRURUN,2020-07-20T11:02:00,-0.17,2021-08-27T00:00:00
5,United States,API Cushing Number,United States API Cushing Number,1.79,2021-09-03T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-cushing-number,Business,,Weekly,UNITEDSTAAPICUSNUM,2020-07-20T11:07:00,2.13,2021-08-27T00:00:00
6,United States,API Distillate Stocks,United States API Distillate Stocks,-3.75,2021-09-03T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-distillate-stocks,Business,,Weekly,UNITEDSTAAPIDISSTO,2020-07-20T11:09:00,-1.96,2021-08-27T00:00:00
7,United States,API Gasoline Stocks,United States API Gasoline Stocks,-6.41,2021-09-03T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-gasoline-stocks,Business,,Weekly,UNITEDSTAAPIGASSTO,2020-07-20T11:11:00,2.71,2021-08-27T00:00:00
8,United States,API Heating Oil,United States API Heating Oil,-0.18,2021-09-03T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-heating-oil,Business,,Weekly,UNITEDSTAAPIHEAOIL,2020-07-20T11:12:00,0.13,2021-08-27T00:00:00
9,United States,API Product Imports,United States API Product Imports,-0.10,2021-09-03T00:00:00,American Petroleum Institute (API),BBL/1Million,/united-states/api-product-imports,Business,,Weekly,UNITEDSTAAPIPROIMP,2020-07-20T11:14:00,0.23,2021-08-27T00:00:00

##### 3 List of indicators by country and group( you can check groups in the "categoryGroup" field of /indicators)
/country/{country}?c=guest:guest&group={group}

http://api.tradingeconomics.com/country/united%20states?c=guest:guest&group=gdp

In [5]:
te.getIndicatorByCategoryGroup(country='united states', category_group='gdp', output_type='df')

,Country,Category,Title,LatestValueDate,LatestValue,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,United States,GDP,United States GDP,2020-12-31T00:00:00,20936.6,World Bank,USD Billion,/united-states/gdp,GDP,Current USD,Yearly,WGDPUS,2014-07-03T16:14:00,21433.22,2019-12-31T00:00:00
1,United States,GDP Annual Growth Rate,United States GDP Annual Growth Rate,2021-06-30T00:00:00,12.2,U.S. Bureau of Economic Analysis,percent,/united-states/gdp-growth-annual,GDP,,Quarterly,GDP CYOY,2014-07-30T15:38:00,0.50,2021-03-31T00:00:00
2,United States,GDP Constant Prices,United States GDP Constant Prices,2021-06-30T00:00:00,19360.6,U.S. Bureau Of Economic Analysis,USD Billion,/united-states/gdp-constant-prices,GDP,"Constant Prices 2012, SA",Quarterly,UNITEDSTAGDPCONPRI,2014-07-25T15:18:00,19055.66,2021-03-31T00:00:00
3,United States,GDP From Agriculture,United States GDP From Agriculture Forestry Fi...,2021-03-31T00:00:00,257.5,U.S. Bureau of Economic Analysis (BEA),USD Billion,/united-states/gdp-from-agriculture,GDP,"Constant Prices 2012, SA",Quarterly,UNITEDSTAGDPFROAGR,2015-08-24T11:15:00,266.20,2020-12-31T00:00:00
4,United States,GDP From Construction,United States GDP From Construction,2021-03-31T00:00:00,684.4,U.S. Bureau of Economic Analysis (BEA),USD Billion,/united-states/gdp-from-construction,GDP,"Constant Prices 2012, SA",Quarterly,UNITEDSTAGDPFROCON,2015-08-24T11:19:00,673.00,2020-12-31T00:00:00
5,United States,GDP From Manufacturing,United States GDP From Manufacturing,2021-03-31T00:00:00,2269.9,U.S. Bureau of Economic Analysis (BEA),USD Billion,/united-states/gdp-from-manufacturing,GDP,"Constant Prices 2012, SA",Quarterly,UNITEDSTAGDPFROMAN,2015-08-24T11:20:00,2234.40,2020-12-31T00:00:00
6,United States,GDP From Mining,United States GDP From Mining,2021-03-31T00:00:00,433.6,U.S. Bureau of Economic Analysis (BEA),USD Billion,/united-states/gdp-from-mining,GDP,"Constant Prices 2012, SA",Quarterly,UNITEDSTAGDPFROMIN,2015-08-24T11:21:00,428.50,2020-12-31T00:00:00
7,United States,GDP From Public Administration,United States GDP From Government,2021-03-31T00:00:00,2180.8,U.S. Bureau of Economic Analysis (BEA),USD Billion,/united-states/gdp-from-public-administration,GDP,"Constant Prices 2012, SA",Quarterly,UNITEDSTAGFPA,2015-08-24T11:22:00,2179.80,2020-12-31T00:00:00
8,United States,GDP From Services,United States GDP From Private Services Produc...,2021-03-31T00:00:00,13167.6,U.S. Bureau of Economic Analysis (BEA),USD Billion,/united-states/gdp-from-services,GDP,"Constant Prices 2012, SA",Quarterly,UNITEDSTAGDPFROSER,2015-08-24T11:23:00,12925.10,2020-12-31T00:00:00
9,United States,GDP From Transport,United States GDP From Transportation and Ware...,2021-03-31T00:00:00,510.2,U.S. Bureau of Economic Analysis (BEA),USD Billion,/united-states/gdp-from-transport,GDP,"Constant Prices 2012, SA",Quarterly,UNITEDSTAGDPFROTRA,2015-08-24T11:18:00,501.80,2020-12-31T00:00:00

##### 4 Specific indicator for all countries
/country/all/{indicator}

https://api.tradingeconomics.com/country/all/gdp?c=guest:guest

In [7]:
te.getIndicatorData(country='all', indicators='gdp', output_type='df')

,Country,Category,Title,LatestValue,LatestValueDate,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,Afghanistan,GDP,Afghanistan GDP,19.81,2020-12-31T00:00:00,World Bank,USD Billion,/afghanistan/gdp,GDP,Current USD,Yearly,AFGSTANGDP,2012-11-07T14:06:00,19.29,2019-12-31T00:00:00
1,Albania,GDP,Albania GDP,14.80,2020-12-31T00:00:00,World Bank,USD Billion,/albania/gdp,GDP,Current USD,Yearly,ALBANIAGDP,2012-10-08T13:36:00,15.29,2019-12-31T00:00:00
2,Algeria,GDP,Algeria GDP,145.16,2020-12-31T00:00:00,World Bank,USD Billion,/algeria/gdp,GDP,Current USD,Yearly,AlgeriaGDP,2011-06-27T00:00:00,171.16,2019-12-31T00:00:00
3,Andorra,GDP,Andorra GDP,3.16,2019-12-31T00:00:00,World Bank,USD Billion,/andorra/gdp,GDP,Current USD,Yearly,ANDORRAGDP,2015-07-07T17:21:00,3.22,2018-12-31T00:00:00
4,Angola,GDP,Angola GDP,62.31,2020-12-31T00:00:00,World Bank,USD Billion,/angola/gdp,GDP,Current USD,Yearly,AngolaGDP,2011-06-27T00:00:00,89.42,2019-12-31T00:00:00
5,Antigua And Barbuda,GDP,Antigua And Barbuda GDP,1.42,2020-12-31T00:00:00,World Bank,USD Billion,/antigua-and-barbuda/gdp,GDP,Current USD,Yearly,ANTIGUAANGDP,2013-08-21T10:34:00,1.66,2019-12-31T00:00:00
6,Argentina,GDP,Argentina GDP,383.10,2020-12-31T00:00:00,World Bank,USD Billion,/argentina/gdp,GDP,Current USD,Yearly,WGDPARGE,2014-07-03T17:34:00,445.50,2019-12-31T00:00:00
7,Armenia,GDP,Armenia GDP,12.65,2020-12-31T00:00:00,World Bank,USD Billion,/armenia/gdp,GDP,Current USD,Yearly,ARMENIAGDP,2012-10-23T15:58:00,13.67,2019-12-31T00:00:00
8,Aruba,GDP,Aruba GDP,3.20,2018-12-31T00:00:00,World Bank,USD Billion,/aruba/gdp,GDP,Current USD,Yearly,ARUBAGDP,2016-02-25T16:11:00,3.09,2017-12-31T00:00:00
9,Australia,GDP,Australia GDP,1330.90,2020-12-31T00:00:00,World Bank,USD Billion,/australia/gdp,GDP,Current USD,Yearly,WGDPAUST,2013-07-04T15:25:00,1396.60,2019-12-31T00:00:00

##### 5 Specific indicator by ticker
/country/ticker/{ticker}

https://api.tradingeconomics.com//country/ticker/usurtot?c=guest:guest

In [6]:
te.getIndicatorByTicker(ticker='usurtot', output_type='df')

,Country,Category,Title,LatestValueDate,LatestValue,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,United States,Unemployment Rate,United States Unemployment Rate,2021-08-31T00:00:00,5.2,U.S. Bureau of Labor Statistics,percent,/united-states/unemployment-rate,Labour,,Monthly,USURTOT,2012-02-23T11:41:00,5.4,2021-07-31T00:00:00

##### 5 Multiple indicators by ticker
/country/ticker/{ticker}

https://api.tradingeconomics.com//country/ticker/usurtot,wgdpchin?c=guest:guest

In [7]:
te.getIndicatorByTicker(ticker=['usurtot','wgdpchin'], output_type='df')

,Country,Category,Title,LatestValueDate,LatestValue,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,China,GDP,China GDP,2020-12-31T00:00:00,14722.73,World Bank,USD Billion,/china/gdp,GDP,Current USD,Yearly,WGDPCHIN,2013-07-04T13:50:00,14279.94,2019-12-31T00:00:00
1,United States,Unemployment Rate,United States Unemployment Rate,2021-08-31T00:00:00,5.20,U.S. Bureau of Labor Statistics,percent,/united-states/unemployment-rate,Labour,,Monthly,USURTOT,2012-02-23T11:41:00,5.40,2021-07-31T00:00:00

## Indicators - Historical

##### 6 Specific country and indicator
/historical/country/{countries}/indicator/{indicators}

https://api.tradingeconomics.com/historical/country/united%20states/indicator/gdp?c=guest:guest

In [8]:
te.getHistoricalData(country='united states', indicator='gdp', output_type='df')

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,United States,GDP,2011-12-31T00:00:00,15542.58,Yearly,WGDPUS,2019-06-25T12:50:00
1,United States,GDP,2012-12-31T00:00:00,16197.01,Yearly,WGDPUS,2019-06-25T12:50:00
2,United States,GDP,2013-12-31T00:00:00,16784.85,Yearly,WGDPUS,2019-06-25T12:50:00
3,United States,GDP,2014-12-31T00:00:00,17527.16,Yearly,WGDPUS,2021-07-05T14:16:00
4,United States,GDP,2015-12-31T00:00:00,18238.30,Yearly,WGDPUS,2021-07-05T14:16:00
5,United States,GDP,2016-12-31T00:00:00,18745.08,Yearly,WGDPUS,2021-07-05T14:17:00
6,United States,GDP,2017-12-31T00:00:00,19542.98,Yearly,WGDPUS,2021-07-05T14:17:00
7,United States,GDP,2018-12-31T00:00:00,20611.86,Yearly,WGDPUS,2021-07-05T14:17:00
8,United States,GDP,2019-12-31T00:00:00,21433.22,Yearly,WGDPUS,2021-07-05T14:17:00
9,United States,GDP,2020-12-31T00:00:00,20936.60,Yearly,WGDPUS,2021-07-02T08:43:00

##### 7  You can specify only a start date for your historical data
/historical/country/{countries}/indicator/{indicators}/{yyyy-mm-dd}

https://api.tradingeconomics.com/historical/country/united%20states/indicator/gdp/2013-01-01?c=guest:guest

In [9]:
te.getHistoricalData(country='united states', indicator='gdp',initDate='2013-01-01', output_type='df')

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,United States,GDP,2013-12-31T00:00:00,16784.85,Yearly,WGDPUS,2019-06-25T12:50:00
1,United States,GDP,2014-12-31T00:00:00,17527.16,Yearly,WGDPUS,2021-07-05T14:16:00
2,United States,GDP,2015-12-31T00:00:00,18238.30,Yearly,WGDPUS,2021-07-05T14:16:00
3,United States,GDP,2016-12-31T00:00:00,18745.08,Yearly,WGDPUS,2021-07-05T14:17:00
4,United States,GDP,2017-12-31T00:00:00,19542.98,Yearly,WGDPUS,2021-07-05T14:17:00
5,United States,GDP,2018-12-31T00:00:00,20611.86,Yearly,WGDPUS,2021-07-05T14:17:00
6,United States,GDP,2019-12-31T00:00:00,21433.22,Yearly,WGDPUS,2021-07-05T14:17:00
7,United States,GDP,2020-12-31T00:00:00,20936.60,Yearly,WGDPUS,2021-07-02T08:43:00

##### 8 or you can specify a start date and end date
/historical/country/{countries}/indicator/{indicators}/{yyyy-mm-dd}/{yyyy-mm-dd}

https://api.tradingeconomics.com/historical/country/united%20states/indicator/gdp/2015-01-01/2015-12-31?c=guest:guest

In [10]:
te.getHistoricalData(country='united states', indicator='gdp',initDate='2013-01-01', endDate='2015-12-31', output_type='df')

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,United States,GDP,2013-12-31T00:00:00,16784.85,Yearly,WGDPUS,2019-06-25T12:50:00
1,United States,GDP,2014-12-31T00:00:00,17527.16,Yearly,WGDPUS,2021-07-05T14:16:00
2,United States,GDP,2015-12-31T00:00:00,18238.30,Yearly,WGDPUS,2021-07-05T14:16:00
3,United States,GDP,2016-12-31T00:00:00,18745.08,Yearly,WGDPUS,2021-07-05T14:17:00
4,United States,GDP,2017-12-31T00:00:00,19542.98,Yearly,WGDPUS,2021-07-05T14:17:00
5,United States,GDP,2018-12-31T00:00:00,20611.86,Yearly,WGDPUS,2021-07-05T14:17:00
6,United States,GDP,2019-12-31T00:00:00,21433.22,Yearly,WGDPUS,2021-07-05T14:17:00
7,United States,GDP,2020-12-31T00:00:00,20936.60,Yearly,WGDPUS,2021-07-02T08:43:00

##### 9 Multiple indicators for specific country
/historical/country/{countries}/indicator/{indicators}

https://api.tradingeconomics.com/historical/country/united%20states/indicator/gdp,population?c=guest:guest

In [11]:
te.getHistoricalData(country='united states', indicator=['gdp', 'population'], output_type='df')

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,United States,GDP,2016-12-31T00:00:00,18745.08,Yearly,WGDPUS,2021-07-05T14:17:00
1,United States,Population,2016-12-31T00:00:00,323.07,Yearly,USA SP.POP.TOTL,2019-07-15T16:25:00
2,United States,GDP,2017-12-31T00:00:00,19542.98,Yearly,WGDPUS,2021-07-05T14:17:00
3,United States,Population,2017-12-31T00:00:00,325.12,Yearly,USA SP.POP.TOTL,2021-02-04T14:21:00
4,United States,GDP,2018-12-31T00:00:00,20611.86,Yearly,WGDPUS,2021-07-05T14:17:00
5,United States,Population,2018-12-31T00:00:00,326.84,Yearly,USA SP.POP.TOTL,2021-02-04T14:21:00
6,United States,GDP,2019-12-31T00:00:00,21433.22,Yearly,WGDPUS,2021-07-05T14:17:00
7,United States,Population,2019-12-31T00:00:00,328.33,Yearly,USA SP.POP.TOTL,2021-02-04T14:21:00
8,United States,GDP,2020-12-31T00:00:00,20936.60,Yearly,WGDPUS,2021-07-02T08:43:00
9,United States,Population,2020-12-31T00:00:00,329.48,Yearly,USA SP.POP.TOTL,2021-02-04T14:22:00

##### 10 Specific indicator for multiple countries
/historical/country/{countries}/indicator/{indicators}

https://api.tradingeconomics.com/historical/country/united%20states,china/indicator/gdp?c=guest:guest

In [12]:
te.getHistoricalData(country=['united states', 'china'], indicator='gdp', output_type='df')

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,China,GDP,2016-12-31T00:00:00,11233.28,Yearly,WGDPCHIN,2020-07-02T11:55:00
1,United States,GDP,2016-12-31T00:00:00,18745.08,Yearly,WGDPUS,2021-07-05T14:17:00
2,China,GDP,2017-12-31T00:00:00,12310.41,Yearly,WGDPCHIN,2020-07-02T11:55:00
3,United States,GDP,2017-12-31T00:00:00,19542.98,Yearly,WGDPUS,2021-07-05T14:17:00
4,China,GDP,2018-12-31T00:00:00,13894.82,Yearly,WGDPCHIN,2020-07-02T11:55:00
5,United States,GDP,2018-12-31T00:00:00,20611.86,Yearly,WGDPUS,2021-07-05T14:17:00
6,China,GDP,2019-12-31T00:00:00,14279.94,Yearly,WGDPCHIN,2021-07-05T14:28:00
7,United States,GDP,2019-12-31T00:00:00,21433.22,Yearly,WGDPUS,2021-07-05T14:17:00
8,China,GDP,2020-12-31T00:00:00,14722.73,Yearly,WGDPCHIN,2021-07-02T08:43:00
9,United States,GDP,2020-12-31T00:00:00,20936.60,Yearly,WGDPUS,2021-07-02T08:43:00

##### 11 Multiple indicators for multiple countries
/historical/country/{countries}/indicator/{indicators}

https://api.tradingeconomics.com/historical/country/united%20states,china/indicator/gdp,population?c=guest:guest

In [13]:
te.getHistoricalData(country=['united states', 'china'], indicator=['gdp','population'], output_type='df')

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,China,GDP,2018-12-31T00:00:00,13894.82,Yearly,WGDPCHIN,2020-07-02T11:55:00
1,China,Population,2018-12-31T00:00:00,1395.38,Yearly,CHN SP.POP.TOTL,2019-04-09T15:10:00
2,China,GDP,2019-12-31T00:00:00,14279.94,Yearly,WGDPCHIN,2021-07-05T14:28:00
3,China,Population,2019-12-31T00:00:00,1400.05,Yearly,CHN SP.POP.TOTL,2020-01-20T13:44:00
4,United States,GDP,2019-12-31T00:00:00,21433.22,Yearly,WGDPUS,2021-07-05T14:17:00
5,United States,Population,2019-12-31T00:00:00,328.33,Yearly,USA SP.POP.TOTL,2021-02-04T14:21:00
6,China,GDP,2020-12-31T00:00:00,14722.73,Yearly,WGDPCHIN,2021-07-02T08:43:00
7,China,Population,2020-12-31T00:00:00,1443.50,Yearly,CHN SP.POP.TOTL,2021-05-14T11:02:00
8,United States,GDP,2020-12-31T00:00:00,20936.60,Yearly,WGDPUS,2021-07-02T08:43:00
9,United States,Population,2020-12-31T00:00:00,329.48,Yearly,USA SP.POP.TOTL,2021-02-04T14:22:00

##### 12 Get historical data by ticker
/historical/ticker/{ticker}/{yyyy-mm-dd}

https://api.tradingeconomics.com/historical/ticker/USURTOT/2015-03-01?c=guest:guest

In [ ]:
done - test here after deploy  te.getHistoricalByTicker(ticker=None, start_date=None, output_type=None)

## Discontinued Series

##### 13 - List of discontinued series for all countries.
/country/all/discontinued

https://api.tradingeconomics.com/country/all/discontinued?c=guest:guest

In [15]:
te.getDiscontinuedIndicator( output_type='df')

https://api.tradingeconomics.com/country/all/discontinued?c=guest:guest

,Country,Category,Title,LatestValueDate,LatestValue,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,Afghanistan,Interest Rate,Afghanistan Interest Rate,2016-12-31T00:00:00,15.00,Afghanistan Bank,percent,/afghanistan/interest-rate,Money,,Monthly,AFGSTANINTTRATE,2014-08-07T17:57:00,15.00,2016-11-30T00:00:00
1,Albania,Changes in Inventories,Albania Changes in Inventories,2016-12-31T00:00:00,128787.00,Instituti i Statistikave (INSTAT),ALL Million,/albania/changes-in-inventories,Business,,Yearly,ALBANIACHAININV,2014-07-28T15:34:00,192706.26,2015-12-31T00:00:00
2,Algeria,Export Prices,Algeria Export Prices,2020-06-30T00:00:00,54.70,Office National des Statistiques (ONS),points,/algeria/export-prices,Prices,"NSA, 2011=000",Quarterly,ALGERIAEXPPRI,2014-08-08T11:55:00,82.70,2020-03-31T00:00:00
3,Algeria,Steel Production,Algeria Steel Production,2014-12-31T00:00:00,35.00,World Steel Association,Thousand Tonnes,/algeria/steel-production,Business,"Volume, NSA",Monthly,AASTEEL,2016-02-16T16:14:00,35.00,2014-11-30T00:00:00
4,Algeria,Terms Of Trade,Algeria Terms Of Trade,2020-06-30T00:00:00,41.70,Office National des Statistiques (ONS),points,/algeria/terms-of-trade,Trade,"2011=100, NSA",Quarterly,ALGERIATEROFTRA,2014-08-08T12:00:00,64.10,2020-03-31T00:00:00
5,Angola,Food Inflation,Luanda Food Inflation,2021-07-31T00:00:00,34.70,"Instituto Nacional de Estatística, Angola",percent,/angola/food-inflation,Prices,"2014M12=100, NSA",Monthly,ANGOLAFOOINF,2014-05-22T15:21:00,33.80,2021-06-30T00:00:00
6,Angola,Gold Reserves,Angola Gold Reserves,2018-10-31T00:00:00,19.07,National Bank of Angola,Tonnes,/angola/gold-reserves,Trade,,Monthly,ANGOLAGOLRES,2014-08-11T14:27:00,19.10,2018-09-30T00:00:00
7,Angola,Living Wage Family,Angola Living Wage Family,2018-12-31T00:00:00,149400.00,WageIndicator Foundation,AOA/Month,/angola/living-wage-family,Labour,,yearly,AngolaLivWagFam,2016-05-25T14:58:00,149400.00,2018-12-31T00:00:00
8,Angola,Living Wage Individual,Angola Living Wage Individual,2018-12-31T00:00:00,61900.00,WageIndicator Foundation,AOA/Month,/angola/living-wage-individual,Labour,,yearly,AngolaLivWagInd,2016-05-25T14:56:00,61900.00,2018-12-31T00:00:00
9,Angola,Money Supply M0,Angola Money Supply M0,2017-09-30T00:00:00,1599755.00,National Bank of Angola,AOA Million,/angola/money-supply-m0,Money,,Monthly,ANGOLAMONSUPM0,2014-08-13T12:59:00,1589837.00,2017-08-31T00:00:00

##### 14  List of discontinued series by country.
/country/{country}/discontinued

https://api.tradingeconomics.com/country/united%20states/discontinued?c=guest:guest

In [14]:
te.getDiscontinuedIndicator(country='united states', output_type='df')

https://api.tradingeconomics.com/country/united%20states/discontinued?c=guest:guest

,Country,Category,Title,LatestValueDate,LatestValue,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,United States,Ism New York Index,United States ISM New York Index,2021-03-31T00:00:00,37.20,Institute for Supply Management,percent,/united-states/ism-new-york-index,Business,SA,Monthly,UNITEDSTAISMNEWYORIN,2014-10-13T17:46:00,35.50,2021-02-28T00:00:00
1,United States,Labor Market Conditions Index,United States Change In Labor Market Condition...,2017-06-30T00:00:00,1.50,Federal Reserve,points,/united-states/labor-market-conditions-index,Labour,SA,Monthly,UNITEDSTALMCI,2015-07-05T12:49:00,3.30,2017-05-31T00:00:00
2,United States,Living Wage Family,United States Living Wage Family,2018-12-31T00:00:00,2380.00,WageIndicator Foundation,USD/Month,/united-states/living-wage-family,Labour,,Yearly,UnitedStLivWagFam,2016-05-25T14:58:00,2270.00,2017-12-31T00:00:00
3,United States,Living Wage Individual,United States Living Wage Individual,2018-12-31T00:00:00,1660.00,WageIndicator Foundation,USD/Month,/united-states/living-wage-individual,Labour,,yearly,UnitedStLivWagInd,2016-05-25T14:56:00,1560.00,2017-12-31T00:00:00
4,United States,Small Business Sentiment,US Small Business Health Index,2015-02-28T00:00:00,51.67,Fit Small Business,,/united-states/small-business-sentiment,Business,,Monthly,UNITEDSTASMABUSSEN,2014-12-22T16:27:00,49.03,2015-01-31T00:00:00
5,United States,Wages High Skilled,United States Wages High Skilled,2018-12-31T00:00:00,4520.00,WageIndicator Foundation,USD/Month,/united-states/wages-high-skilled,Labour,,yearly,UnitedStWagHigSki,2016-02-03T14:53:00,4330.00,2017-12-31T00:00:00
6,United States,Wages Low Skilled,United States Wages Low Skilled,2018-12-31T00:00:00,1960.00,WageIndicator Foundation,USD/Month,/united-states/wages-low-skilled,Labour,,Yearly,UnitedStWagLowSki,2016-02-03T15:00:00,1760.00,2017-12-31T00:00:00

###### 14 List of discontinued series with multiple countries.
/country/{countries}/discontinued

https://api.tradingeconomics.com/country/united%20states,china/discontinued?c=guest:guest

In [16]:
te.getDiscontinuedIndicator(country=['united states','China'], output_type='df')

https://api.tradingeconomics.com/country/united%20states%2CChina/discontinued?c=guest:guest

,Country,Category,Title,LatestValueDate,LatestValue,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,China,Gdp From Mining,China Gdp From Mining,2018-12-31T00:00:00,22592.00,National Bureau of Statistics of China,CNY HML,/china/gdp-from-mining,GDP,"Current Prices, NSA",Yearly,CHINAGDPFROMIN,2021-01-13T15:54:00,21026.0,2017-12-31T00:00:00
1,China,Home Ownership Rate,China Home Ownership Rate,2018-12-31T00:00:00,89.68,Peking University Institute of Social Sciences,percent,/china/home-ownership-rate,Housing,,Yearly,CHINAHOMOWNRAT,2015-08-12T14:43:00,90.0,2014-12-31T00:00:00
2,China,Job Vacancies,China Job Vacancies,2018-12-31T00:00:00,4380000.00,Ministry of Human Resources and Social Securit...,,/china/job-vacancies,Labour,NSA,Quarterly,CHINAJOBVAC,2013-06-23T16:56:00,4890000.0,2018-09-30T00:00:00
3,China,Leading Economic Index,China Leading Economic Index,2021-06-30T00:00:00,100.40,National Bureau of Statistics of China,points,/china/leading-economic-index,Business,1996=100,Monthly,CHINALEAECOIND,2014-07-10T15:13:00,101.8,2021-05-31T00:00:00
4,China,Mni Business Sentiment,MNI China Business Sentiment Indicator,2016-12-31T00:00:00,55.90,MNI Deutsche Börse Group,,/china/mni-business-sentiment,Business,SA,Monthly,CHINAMNIBUSSEN,2015-12-09T11:49:00,53.1,2016-11-30T00:00:00
5,China,Mni Consumer Sentiment,China Westpac MNI Consumer Sentiment Indicator,2016-12-31T00:00:00,116.60,MNI Deutsche Börse Group,,/china/mni-consumer-sentiment,Consumer,SA,Monthly,CHINAMNICONSEN,2016-02-03T16:45:00,114.9,2016-11-30T00:00:00
6,China,Personal Savings,China Net Household Saving Rate,2016-12-31T00:00:00,36.10,OECD,percent,/china/personal-savings,Consumer,,Yearly,CHINAPERSAV,2012-09-28T20:02:00,37.1,2015-12-31T00:00:00
7,United States,Ism New York Index,United States ISM New York Index,2021-03-31T00:00:00,37.20,Institute for Supply Management,percent,/united-states/ism-new-york-index,Business,SA,Monthly,UNITEDSTAISMNEWYORIN,2014-10-13T17:46:00,35.5,2021-02-28T00:00:00
8,United States,Labor Market Conditions Index,United States Change In Labor Market Condition...,2017-06-30T00:00:00,1.50,Federal Reserve,points,/united-states/labor-market-conditions-index,Labour,SA,Monthly,UNITEDSTALMCI,2015-07-05T12:49:00,3.3,2017-05-31T00:00:00
9,United States,Living Wage Family,United States Living Wage Family,2018-12-31T00:00:00,2380.00,WageIndicator Foundation,USD/Month,/united-states/living-wage-family,Labour,,Yearly,UnitedStLivWagFam,2016-05-25T14:58:00,2270.0,2017-12-31T00:00:00

## Indicators - Forecasts

####  15 Specific country
/forecast/country/{country}

https://api.tradingeconomics.com/forecast/country/united%20states?c=guest:guest

In [3]:
te.getForecastData(country='united states', output_type='df')

,Country,Category,LatestValue,LatestValueDate,YearEnd,YearEnd2,YearEnd3,q1,q1_date,q2,q2_date,q3,q3_date,q4,q4_date,Frequency,HistoricalDataSymbol
0,United States,ADP Employment Change,374.00,2021-08-31T00:00:00,250.00,150.00,210.00,350.00,2021-09-30T00:00:00,250.00,2021-12-31T00:00:00,190.00,2022-03-31T00:00:00,200.0,2022-06-30T00:00:00,Monthly,UNITEDSTAADPEMPCHA
1,United States,API Crude Oil Stock Change,-5.44,2021-09-10T00:00:00,-2.00,2.00,0.50,-5.00,2021-09-30T00:00:00,-2.00,2021-12-31T00:00:00,4.00,2022-03-31T00:00:00,4.0,2022-06-30T00:00:00,Weekly,APICRUDEOIL
2,United States,Average Hourly Earnings,0.60,2021-08-31T00:00:00,0.20,0.20,0.20,0.40,2021-09-30T00:00:00,0.20,2021-12-31T00:00:00,0.20,2022-03-31T00:00:00,0.3,2022-06-30T00:00:00,Monthly,UNITEDSTAAVEHOUEAR
3,United States,Average Weekly Hours,34.70,2021-08-31T00:00:00,34.60,34.40,34.40,34.70,2021-09-30T00:00:00,34.60,2021-12-31T00:00:00,34.80,2022-03-31T00:00:00,34.6,2022-06-30T00:00:00,Monthly,UNITEDSTAAVEWEEHOU
4,United States,Balance of Trade,-70051.00,2021-07-31T00:00:00,-63000.00,-63000.00,-55000.00,-60000.00,2021-09-30T00:00:00,-63000.00,2021-12-31T00:00:00,-52000.00,2022-03-31T00:00:00,-59999.0,2022-06-30T00:00:00,Monthly,USTBTOT
5,United States,Bank Lending Rate,3.25,2021-08-31T00:00:00,3.25,3.75,3.75,3.25,2021-09-30T00:00:00,3.25,2021-12-31T00:00:00,3.25,2022-03-31T00:00:00,3.5,2022-06-30T00:00:00,Monthly,UNITEDSTABANLENRAT
6,United States,Bankruptcies,18511.00,2021-06-30T00:00:00,20300.00,22000.00,21000.00,18000.00,2021-09-30T00:00:00,20300.00,2021-12-31T00:00:00,22500.00,2022-03-31T00:00:00,23000.0,2022-06-30T00:00:00,Quarterly,UNITEDSTABAN
7,United States,Banks Balance Sheet,22142.40,2021-09-01T00:00:00,20656.00,20556.00,20800.00,21000.00,2021-09-30T00:00:00,20656.00,2021-12-31T00:00:00,20600.00,2022-03-31T00:00:00,20550.0,2022-06-30T00:00:00,Weekly,UNITEDSTABANBALSHE
8,United States,Building Permits,1630.00,2021-07-31T00:00:00,1400.00,1300.00,1300.00,1470.00,2021-09-30T00:00:00,1400.00,2021-12-31T00:00:00,1350.00,2022-03-31T00:00:00,1300.0,2022-06-30T00:00:00,Monthly,UNITEDSTABUIPER
9,United States,Business Confidence,59.90,2021-08-31T00:00:00,56.40,53.40,52.40,57.00,2021-09-30T00:00:00,56.40,2021-12-31T00:00:00,53.00,2022-03-31T00:00:00,55.0,2022-06-30T00:00:00,Monthly,NAPMPMI

#### 16  Multiple countries
/forecast/country/{countries}

https://api.tradingeconomics.com/forecast/country/united%20states,china?c=guest:guest

In [12]:
te.getForecastData(country=['united states','china'], output_type='df')

,Country,Category,LatestValue,LatestValueDate,YearEnd,YearEnd2,YearEnd3,q1,q1_date,q2,q2_date,q3,q3_date,q4,q4_date,Frequency,HistoricalDataSymbol
0,United States,ADP Employment Change,374.00,2021-08-31T00:00:00,250.00,150.00,210.00,350.00,2021-09-30T00:00:00,250.00,2021-12-31T00:00:00,190.00,2022-03-31T00:00:00,200.00,2022-06-30T00:00:00,Monthly,UNITEDSTAADPEMPCHA
1,United States,API Crude Oil Stock Change,-5.44,2021-09-10T00:00:00,-2.00,2.00,0.50,-5.00,2021-09-30T00:00:00,-2.00,2021-12-31T00:00:00,4.00,2022-03-31T00:00:00,4.00,2022-06-30T00:00:00,Weekly,APICRUDEOIL
2,United States,Average Hourly Earnings,0.60,2021-08-31T00:00:00,0.20,0.20,0.20,0.40,2021-09-30T00:00:00,0.20,2021-12-31T00:00:00,0.20,2022-03-31T00:00:00,0.30,2022-06-30T00:00:00,Monthly,UNITEDSTAAVEHOUEAR
3,United States,Average Weekly Hours,34.70,2021-08-31T00:00:00,34.60,34.40,34.40,34.70,2021-09-30T00:00:00,34.60,2021-12-31T00:00:00,34.80,2022-03-31T00:00:00,34.60,2022-06-30T00:00:00,Monthly,UNITEDSTAAVEWEEHOU
4,China,Balance of Trade,583.31,2021-08-31T00:00:00,210.00,910.00,950.00,267.00,2021-09-30T00:00:00,210.00,2021-12-31T00:00:00,420.00,2022-03-31T00:00:00,700.00,2022-06-30T00:00:00,Monthly,CNFRBALD
5,United States,Balance of Trade,-70051.00,2021-07-31T00:00:00,-63000.00,-63000.00,-55000.00,-60000.00,2021-09-30T00:00:00,-63000.00,2021-12-31T00:00:00,-52000.00,2022-03-31T00:00:00,-59999.00,2022-06-30T00:00:00,Monthly,USTBTOT
6,China,Bank Lending Rate,2.95,2021-09-10T00:00:00,2.95,2.95,2.95,2.95,2021-09-30T00:00:00,2.95,2021-12-31T00:00:00,2.95,2022-03-31T00:00:00,2.95,2022-06-30T00:00:00,Daily,CHINABANLENRAT
7,United States,Bank Lending Rate,3.25,2021-08-31T00:00:00,3.25,3.75,3.75,3.25,2021-09-30T00:00:00,3.25,2021-12-31T00:00:00,3.25,2022-03-31T00:00:00,3.50,2022-06-30T00:00:00,Monthly,UNITEDSTABANLENRAT
8,United States,Bankruptcies,18511.00,2021-06-30T00:00:00,20300.00,22000.00,21000.00,18000.00,2021-09-30T00:00:00,20300.00,2021-12-31T00:00:00,22500.00,2022-03-31T00:00:00,23000.00,2022-06-30T00:00:00,Quarterly,UNITEDSTABAN
9,China,Banks Balance Sheet,1220.00,2021-08-31T00:00:00,1300.00,1800.00,1800.00,1250.00,2021-09-30T00:00:00,1300.00,2021-12-31T00:00:00,1700.00,2022-03-31T00:00:00,1400.00,2022-06-30T00:00:00,Monthly,CHINABANBALSHE

#### 17 Specific indicator
/forecast/indicator/{indicator}

https://api.tradingeconomics.com/forecast/indicator/gdp?c=guest:guest

In [39]:
te.getForecastData(indicator='gdp', output_type='df')

,Country,Category,LatestValue,LatestValueDate,YearEnd,YearEnd2,YearEnd3,q1,q1_date,q2,q2_date,q3,q3_date,q4,q4_date,Frequency,HistoricalDataSymbol
0,Afghanistan,GDP,19.81,2020-12-31T00:00:00,20.46,21.43,21.43,20.46,2021-09-30T00:00:00,20.46,2021-12-31T00:00:00,20.46,2022-03-31T00:00:00,20.46,2022-06-30T00:00:00,Yearly,AFGSTANGDP
1,Albania,GDP,14.80,2020-12-31T00:00:00,17.12,18.29,19.50,17.12,2021-09-30T00:00:00,17.12,2021-12-31T00:00:00,18.29,2022-03-31T00:00:00,18.29,2022-06-30T00:00:00,Yearly,ALBANIAGDP
2,Algeria,GDP,145.16,2020-12-31T00:00:00,155.00,165.00,165.00,155.00,2021-09-30T00:00:00,155.00,2021-12-31T00:00:00,155.00,2022-03-31T00:00:00,155.00,2022-06-30T00:00:00,Yearly,AlgeriaGDP
3,Andorra,GDP,3.16,2019-12-31T00:00:00,3.40,3.70,3.70,3.40,2021-09-30T00:00:00,3.40,2021-12-31T00:00:00,3.40,2022-03-31T00:00:00,3.40,2022-06-30T00:00:00,Yearly,ANDORRAGDP
4,Angola,GDP,62.31,2020-12-31T00:00:00,100.00,118.00,118.00,100.00,2021-09-30T00:00:00,100.00,2021-12-31T00:00:00,100.00,2022-03-31T00:00:00,100.00,2022-06-30T00:00:00,Yearly,AngolaGDP
5,Antigua And Barbuda,GDP,1.42,2020-12-31T00:00:00,1.64,1.70,1.70,1.64,2021-09-30T00:00:00,1.64,2021-12-31T00:00:00,1.64,2022-03-31T00:00:00,1.64,2022-06-30T00:00:00,Yearly,ANTIGUAANGDP
6,Argentina,GDP,383.10,2020-12-31T00:00:00,425.00,437.00,443.00,425.00,2021-09-30T00:00:00,425.00,2021-12-31T00:00:00,437.00,2022-03-31T00:00:00,437.00,2022-06-30T00:00:00,Yearly,WGDPARGE
7,Armenia,GDP,12.65,2020-12-31T00:00:00,11.00,14.00,14.00,11.00,2021-09-30T00:00:00,11.00,2021-12-31T00:00:00,11.00,2022-03-31T00:00:00,11.00,2022-06-30T00:00:00,Yearly,ARMENIAGDP
8,Aruba,GDP,3.20,2018-12-31T00:00:00,2.60,2.70,2.70,2.60,2021-09-30T00:00:00,2.60,2021-12-31T00:00:00,2.60,2022-03-31T00:00:00,2.60,2022-06-30T00:00:00,Yearly,ARUBAGDP
9,Australia,GDP,1330.90,2020-12-31T00:00:00,1370.00,1450.00,1550.00,1370.00,2021-09-30T00:00:00,1370.00,2021-12-31T00:00:00,1450.00,2022-03-31T00:00:00,1450.00,2022-06-30T00:00:00,Yearly,WGDPAUST

#### 17 -Multiple indicators
/forecast/indicator/{indicators}

https://api.tradingeconomics.com/forecast/indicator/gdp,population?c=guest:guest

In [40]:
te.getForecastData(indicator=['gdp','population'], output_type='df')

,Country,Category,LatestValue,LatestValueDate,YearEnd,YearEnd2,YearEnd3,q1,q1_date,q2,q2_date,q3,q3_date,q4,q4_date,Frequency,HistoricalDataSymbol
0,Afghanistan,GDP,19.81,2020-12-31T00:00:00,20.46,21.43,21.43,20.46,2021-09-30T00:00:00,20.46,2021-12-31T00:00:00,20.46,2022-03-31T00:00:00,20.46,2022-06-30T00:00:00,Yearly,AFGSTANGDP
1,Afghanistan,Population,33.20,2020-12-31T00:00:00,37.30,39.20,39.20,37.30,2021-09-30T00:00:00,37.30,2021-12-31T00:00:00,37.30,2022-03-31T00:00:00,37.30,2022-06-30T00:00:00,Yearly,AFGSTANPOPLATION
2,Albania,GDP,14.80,2020-12-31T00:00:00,17.12,18.29,19.50,17.12,2021-09-30T00:00:00,17.12,2021-12-31T00:00:00,18.29,2022-03-31T00:00:00,18.29,2022-06-30T00:00:00,Yearly,ALBANIAGDP
3,Albania,Population,2.85,2020-12-31T00:00:00,2.84,2.83,2.83,2.84,2021-09-30T00:00:00,2.84,2021-12-31T00:00:00,2.84,2022-03-31T00:00:00,2.84,2022-06-30T00:00:00,Yearly,ALBANIAPOPLATION
4,Algeria,GDP,145.16,2020-12-31T00:00:00,155.00,165.00,165.00,155.00,2021-09-30T00:00:00,155.00,2021-12-31T00:00:00,155.00,2022-03-31T00:00:00,155.00,2022-06-30T00:00:00,Yearly,AlgeriaGDP
5,Algeria,Population,44.23,2020-12-31T00:00:00,45.50,46.60,46.60,45.20,2021-09-30T00:00:00,45.50,2021-12-31T00:00:00,45.50,2022-03-31T00:00:00,45.50,2022-06-30T00:00:00,Yearly,DZA SP.POP.TOTL
6,Andorra,GDP,3.16,2019-12-31T00:00:00,3.40,3.70,3.70,3.40,2021-09-30T00:00:00,3.40,2021-12-31T00:00:00,3.40,2022-03-31T00:00:00,3.40,2022-06-30T00:00:00,Yearly,ANDORRAGDP
7,Angola,GDP,62.31,2020-12-31T00:00:00,100.00,118.00,118.00,100.00,2021-09-30T00:00:00,100.00,2021-12-31T00:00:00,100.00,2022-03-31T00:00:00,100.00,2022-06-30T00:00:00,Yearly,AngolaGDP
8,Angola,Population,33.00,2020-12-30T00:00:00,33.78,34.77,34.77,33.60,2021-09-30T00:00:00,33.78,2021-12-31T00:00:00,33.78,2022-03-31T00:00:00,33.78,2022-06-30T00:00:00,Yearly,AngolaPopulation
9,Antigua And Barbuda,GDP,1.42,2020-12-31T00:00:00,1.64,1.70,1.70,1.64,2021-09-30T00:00:00,1.64,2021-12-31T00:00:00,1.64,2022-03-31T00:00:00,1.64,2022-06-30T00:00:00,Yearly,ANTIGUAANGDP

#### 18 Forecast by specific ticker
/forecast/ticker/{ticker}

https://api.tradingeconomics.com//forecast/ticker/usurtot?c=guest:guest

In [8]:
te.getForecastByTicker(ticker='usurtot', output_type='df')

https://api.tradingeconomics.com/forecast/ticker/usurtot?c=guest:guest

,Country,Category,Title,LatestValue,LatestValueDate,q1,q2,q3,q4,YearEnd,YearEnd2,YearEnd3,q1_date,q2_date,q3_date,q4_date,Frequency,HistoricalDataSymbol
0,United States,Unemployment Rate,United States Unemployment Rate,5.2,2021-08-31T00:00:00,5.1,5.2,5.2,5.0,5.2,5.0,4.3,2021-09-30T00:00:00,2021-12-31T00:00:00,2022-03-31T00:00:00,2022-06-30T00:00:00,Monthly,USURTOT

#### 18 Forecasts by multiple tickers
/forecast/ticker/{tickers}

https://api.tradingeconomics.com//forecast/ticker/usurtot,wgdpchin?c=guest:guest

In [9]:
te.getForecastByTicker(ticker=['usurtot','wgdpchin'], output_type='df')

https://api.tradingeconomics.com/forecast/ticker/usurtot%2Cwgdpchin?c=guest:guest

,Country,Category,Title,LatestValue,LatestValueDate,q1,q2,q3,q4,YearEnd,YearEnd2,YearEnd3,q1_date,q2_date,q3_date,q4_date,Frequency,HistoricalDataSymbol
0,United States,Unemployment Rate,United States Unemployment Rate,5.20,2021-08-31T00:00:00,5.1,5.2,5.2,5.0,5.2,5.0,4.3,2021-09-30T00:00:00,2021-12-31T00:00:00,2022-03-31T00:00:00,2022-06-30T00:00:00,Monthly,USURTOT
1,China,GDP,China GDP,14722.73,2020-12-31T00:00:00,14600.0,14600.0,15700.0,15700.0,14600.0,15700.0,16400.0,2021-09-30T00:00:00,2021-12-31T00:00:00,2022-03-31T00:00:00,2022-06-30T00:00:00,Yearly,WGDPCHIN

#### 19 Specific country and indicator
/forecast/country/{country}/indicator/{indicator}

https://api.tradingeconomics.com/forecast/country/united%20states/indicator/gdp?c=guest:guest

In [30]:
te.getIndicatorData(country='united states', indicators='gdp', output_type='df')

,Country,Category,Title,LatestValue,LatestValueDate,Source,Unit,URL,CategoryGroup,Adjustment,Frequency,HistoricalDataSymbol,CreateDate,PreviousValue,PreviousValueDate
0,United States,GDP,United States GDP,20936.6,2020-12-31T00:00:00,World Bank,USD Billion,/united-states/gdp,GDP,Current USD,Yearly,WGDPUS,2014-07-03T16:14:00,21433.22,2019-12-31T00:00:00

#### 19 Multiple countries and indicators
/forecast/country/{countries}/indicator/{indicators}

https://api.tradingeconomics.com/forecast/country/united%20states,china/indicator/gdp,population?c=guest:guest

In [33]:
te.getForecastData(country = ['United States', 'china'], indicator = ['gdp', 'population'], output_type='df')

,Country,Category,LatestValue,LatestValueDate,YearEnd,YearEnd2,YearEnd3,q1,q1_date,q2,q2_date,q3,q3_date,q4,q4_date,Frequency,HistoricalDataSymbol
0,China,GDP,14722.73,2020-12-31T00:00:00,14600.00,15700.00,16400.00,14600.00,2021-09-30T00:00:00,14600.00,2021-12-31T00:00:00,15700.00,2022-03-31T00:00:00,15700.00,2022-06-30T00:00:00,Yearly,WGDPCHIN
1,United States,GDP,20936.60,2020-12-31T00:00:00,21500.00,22790.00,22790.00,21500.00,2021-09-30T00:00:00,21500.00,2021-12-31T00:00:00,21500.00,2022-03-31T00:00:00,21500.00,2022-06-30T00:00:00,Yearly,WGDPUS
2,China,Population,1443.50,2020-12-31T00:00:00,1465.00,1495.00,1540.00,1465.00,2021-09-30T00:00:00,1465.00,2021-12-31T00:00:00,1495.00,2022-03-31T00:00:00,1495.00,2022-06-30T00:00:00,Yearly,CHN SP.POP.TOTL
3,United States,Population,329.48,2020-12-31T00:00:00,333.23,335.25,335.25,331.21,2021-09-30T00:00:00,333.23,2021-12-31T00:00:00,333.23,2022-03-31T00:00:00,333.23,2022-06-30T00:00:00,Yearly,USA SP.POP.TOTL

## Indicators - Credit Rating

##### 20 Latest Credit Ratings.
/ratings

https://api.tradingeconomics.com/ratings?c=guest:guest

In [11]:
te.getRatings(output_type='df')

,Country,TE,TE_Outlook,SP,SP_Outlook,Moodys,Moodys_Outlook,Fitch,Fitch_Outlook,Outlook,DBRS,DBRS_Outlook
0,Albania,35,Stable,B+,Stable,B1,Stable,,,NaN,,
1,Andorra,62,Positive,BBB,Stable,,,BBB+,Stable,NaN,,
2,Angola,20,Stable,CCC+,Stable,B3,Stable,CCC,N/A,NaN,,
3,Argentina,15,Stable,CCC+,Stable,Ca,Stable,CCC,N/A,NaN,CCC,Stable
4,Armenia,16,Negative,,,Ba3,Stable,B+,Stable,NaN,,
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Uruguay,55,Negative,\tBBB,Stable,Baa2,Stable,BBB-,Negative,NaN,BBB (low),Stable
151,Uzbekistan,38,Stable,BB-,Stable,B1,Positive,BB-,Stable,NaN,,
152,Venezuela,11,Negative Watch,SD,N/A,WR,N/A,RD,N/A,NaN,,
153,Vietnam,43,Stable,BB,Positive,Ba3,Positive,BB,Positive,NaN,,
154,Zambia,30,Negative,SD,N/A,Ca,Stable,RD,N/A,NaN,,

##### 21 Credit Rating of the specific country
/ratings/{country}

https://api.tradingeconomics.com/ratings/united%20states?c=guest:guest

In [12]:
te.getRatings(country='united states', output_type='df')

,Country,TE,TE_Outlook,SP,SP_Outlook,Moodys,Moodys_Outlook,Fitch,Fitch_Outlook,Outlook,DBRS,DBRS_Outlook
0,United States,98,Stable,AA+,Stable,Aaa,Stable,AAA,Negative,NaN,AAA,Stable

##### 21 Credit Rating for multiple countries
/ratings/{countries}

https://api.tradingeconomics.com/ratings/united%20states,portugal?c=guest:guest

In [13]:
te.getRatings(country=['united states','china'], output_type='df')

,Country,TE,TE_Outlook,SP,SP_Outlook,Moodys,Moodys_Outlook,Fitch,Fitch_Outlook,Outlook,DBRS,DBRS_Outlook
0,China,80,Stable,A+,Stable,A1,Stable,A+,Stable,NaN,A (high),Stable
1,United States,98,Stable,AA+,Stable,Aaa,Stable,AAA,Negative,NaN,AAA,Stable

##### 22 Historical credit rating for one country
/ratings/historical/{country}

https://api.tradingeconomics.com/ratings/historical/united%20states?c=guest:guest

In [15]:
te.getHistoricalRatings(country='united states', output_type='df')

          Country        Date   Agency Rating         Outlook
0   United States   7/31/2020    Fitch    AAA        Negative
1   United States   4/22/2014     DBRS    AAA          Stable
2   United States   3/21/2014    Fitch    AAA          Stable
3   United States  10/15/2013    Fitch    AAA  Negative Watch
4   United States   10/9/2013     DBRS    AAA    Under Review
5   United States   7/18/2013  Moody's    Aaa          Stable
6   United States   6/10/2013      S&P    AA+          Stable
7   United States  11/28/2011    Fitch    AAA        Negative
8   United States    9/8/2011     DBRS    AAA          Stable
9   United States    8/5/2011      S&P    AA+        Negative
10  United States    8/2/2011  Moody's    Aaa        Negative
11  United States   7/14/2011      S&P    AAA  Negative Watch
12  United States   7/13/2011  Moody's    Aaa  Negative Watch
13  United States   4/18/2011      S&P    AAA        Negative
14  United States   9/21/2000    Fitch    AAA          Stable
15  United States    4/1/1996    Fitch    AAA             N/A
16  United States  11/13/1995    Fitch    AAA  Negative Watch
17  United States   8/10/1994    Fitch    AAA             N/A
18  United States    2/5/1949  Moody's    Aaa          Stable

##### 22 Historical credit rating for multiple countries
/ratings/historical/{countries}

https://api.tradingeconomics.com/ratings/historical/united%20states,portugal?c=guest:guest

In [16]:
te.getHistoricalRatings(country=['united states','portugal'], output_type='df')

          Country        Date   Agency      Rating   Outlook
0   United States   7/31/2020    Fitch         AAA  Negative
1        Portugal   4/24/2020      S&P         BBB    Stable
2        Portugal   4/17/2020    Fitch         BBB    Stable
3        Portugal   10/4/2019     DBRS  BBB (high)    Stable
4        Portugal   9/13/2019      S&P         BBB  Positive
..            ...         ...      ...         ...       ...
91       Portugal  10/26/1989      S&P           A    Stable
92       Portugal   6/26/1989      S&P           A  Positive
93       Portugal   10/1/1988      S&P           A       N/A
94       Portugal  11/18/1986  Moody's          A1    Stable
95  United States    2/5/1949  Moody's         Aaa    Stable

[96 rows x 5 columns]

##### 23 Historical credit rating by start and end date
/ratings/historical/{country}/{yyyy-mm-dd}/{yyyy-mm-dd}

https://api.tradingeconomics.com/ratings/historical/united%20states/2011-01-01/2012-01-01?c=guest:guest

In [17]:
te.getHistoricalRatings(country = 'United States', initDate ='2011-01-01', endDate = '2012-01-01', output_type='df')

         Country        Date   Agency Rating         Outlook
0  United States  11/28/2011    Fitch    AAA        Negative
1  United States    9/8/2011     DBRS    AAA          Stable
2  United States    8/5/2011      S&P    AA+        Negative
3  United States    8/2/2011  Moody's    Aaa        Negative
4  United States   7/14/2011      S&P    AAA  Negative Watch
5  United States   7/13/2011  Moody's    Aaa  Negative Watch
6  United States   4/18/2011      S&P    AAA        Negative

##### 24 You can specify only a start date
/ratings/historical/{country}/{yyyy-mm-dd}

https://api.tradingeconomics.com/ratings/historical/united%20states/2011-01-01/2012-01-01?c=guest:guest

In [18]:
te.getHistoricalRatings(country = 'United States', initDate ='2011-01-01', output_type='df')

          Country        Date   Agency Rating         Outlook
0   United States   7/31/2020    Fitch    AAA        Negative
1   United States   4/22/2014     DBRS    AAA          Stable
2   United States   3/21/2014    Fitch    AAA          Stable
3   United States  10/15/2013    Fitch    AAA  Negative Watch
4   United States   10/9/2013     DBRS    AAA    Under Review
5   United States   7/18/2013  Moody's    Aaa          Stable
6   United States   6/10/2013      S&P    AA+          Stable
7   United States  11/28/2011    Fitch    AAA        Negative
8   United States    9/8/2011     DBRS    AAA          Stable
9   United States    8/5/2011      S&P    AA+        Negative
10  United States    8/2/2011  Moody's    Aaa        Negative
11  United States   7/14/2011      S&P    AAA  Negative Watch
12  United States   7/13/2011  Moody's    Aaa  Negative Watch
13  United States   4/18/2011      S&P    AAA        Negative

## Latest updates

##### 25 Latest updates
/updates

https://api.tradingeconomics.com/updates?client=guest:guest

In [19]:
te.getLatestUpdates(output_type = 'df')

,Country,Category,HistoricalDataSymbol,LastUpdate
0,United States,Consumer Confidence,CONCCONF,2021-09-17T14:17:00
1,Nigeria,Interest Rate,NIGERIAINTRATE,2021-09-17T14:16:00
2,Azerbaijan,Interest Rate,AZEIJANINTTRATE,2021-09-17T13:56:00
3,Bahrain,Money Supply M1,BAHRAINMONSUPM1,2021-09-17T13:32:00
4,Bahrain,Money Supply M2,BAHRAINMONSUPM2,2021-09-17T13:32:00
5,Serbia,Capital Flows,SERBIACAPFLO,2021-09-17T13:21:00
6,Serbia,Current Account,SERRBIACURCOUNT,2021-09-17T13:20:00
7,Lebanon,Inflation Rate,LEBANONINFNRATE,2021-09-17T13:13:00
8,Zimbabwe,Inflation Rate,ZIMABWEINFNRATE,2021-09-17T13:09:00
9,Zimbabwe,Inflation Rate Mom,ZIMBABWEINFRATMOM,2021-09-17T13:09:00

##### 26 Updates since a start date
/updates/{date}

https://api.tradingeconomics.com/updates/2018-01-01?client=guest:guest

In [20]:
te.getLatestUpdates(initDate = '2018-08-15', output_type = 'df')

,Country,Category,HistoricalDataSymbol,LastUpdate
0,Australia,Calendar,,2020-01-10T16:08:00
1,Japan,Calendar,,2020-11-17T09:23:00
2,Zimbabwe,Internet Speed,ZWEKBPS,2021-07-13T23:17:00
3,Zimbabwe,Personal Income Tax Rate,ZWEIRSTAX,2021-07-13T23:17:00
4,Zimbabwe,IP Addresses,ZWEIPS,2021-07-13T23:17:00
5,Zimbabwe,Ease of Doing Business,ZWEICBUSEASEXQ,2021-07-13T23:17:00
6,Zimbabwe,Corporate Tax Rate,ZWECORPTAX,2021-07-13T23:17:00
7,Zimbabwe,Tourist Arrivals,ZIMBABWETOUARR,2021-07-13T23:17:00
8,Zimbabwe,Terrorism Index,ZIMBABWETERIND,2021-07-13T23:17:00
9,Zimbabwe,Sales Tax Rate,ZIMBABWESALTAXRAT,2021-07-13T23:17:00

##### 27 Get the Latest Updates by country.
/updates/country/{country}

https://api.tradingeconomics.com/updates/country/portugal?client=guest:guest

In [10]:
te.getLatestUpdates(country='portugal', output_type='df')

,Country,Category,HistoricalDataSymbol,LastUpdate
0,Portugal,Labor Force Participation Rate,PORTUGALLABFORPARRAT,2021-09-21T11:18:00
1,Portugal,Credit Rating,,2021-09-21T10:15:00
2,Portugal,Coronavirus Vaccination Total,PTCOVIDVT,2021-09-21T02:25:00
3,Portugal,Coronavirus Recovered,PTCOVIDRT,2021-09-21T02:24:00
4,Portugal,Coronavirus Vaccination Rate,PTCOVIDVR,2021-09-21T02:24:00
5,Portugal,Current Account,PTCUEURO,2021-09-20T11:35:00
6,Portugal,Capital Flows,PORTUGALCAPFLO,2021-09-20T10:25:00
7,Portugal,Foreign Direct Investment,PORTUGALFORDIRINV,2021-09-20T10:25:00
8,Portugal,Tourist Arrivals,PORTUGALTOUARR,2021-09-18T10:12:00
9,Portugal,Central Bank Balance Sheet,PORTUGALCENBANBALSHE,2021-09-18T10:10:00

##### 28 Get the Latest Updates by country since a start date
/updates/country/{country}/{date}

https://api.tradingeconomics.com/updates/country/portugal/2018-01-01?client=guest:guest

In [11]:
te.getLatestUpdates(country='portugal', init_date='2018-01-01', output_type='df')

,Country,Category,HistoricalDataSymbol,LastUpdate
0,Portugal,GDP,WGDPPORT,2021-07-13T23:17:00
1,Portugal,Government Budget,WCSDPRT,2021-07-13T23:17:00
2,Portugal,Nurses,PTNURS,2021-07-13T23:17:00
3,Portugal,ICU Beds,PTICUB,2021-07-13T23:17:00
4,Portugal,Hospitals,PTHOSP,2021-07-13T23:17:00
5,Portugal,Hospital Beds,PTBEDS,2021-07-13T23:17:00
6,Portugal,Social Security Rate For Employees,PRTSSRE,2021-07-13T23:17:00
7,Portugal,Social Security Rate For Companies,PRTSSRC,2021-07-13T23:17:00
8,Portugal,Social Security Rate,PRTSSR,2021-07-13T23:17:00
9,Portugal,Sales Tax Rate,PRTSALESTAX,2021-07-13T23:17:00