In [1]:
import tradingeconomics as te
te.login()

'You are logged in as a guest:guest'

# Markets

## Markets List

##### 1  Commodities
/markets/commodities
https://api.tradingeconomics.com/markets/commodities?c=guest:guest

In [2]:
te.getMarketsData(marketsField='commodities', output_type='df')

,Symbol,Ticker,Name,Country,Date,Last,Close,CloseDate,Group,URL,...,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,decimals,unit,frequency,LastUpdate
0,BDIY:IND,BALTIC,Baltic Dry,commodity,2021-09-16T00:00:00,4215.000,4215.000,2021-09-16T00:00:00,Index,/commodity/baltic,...,208.5652,4233.000,3643.000,3657.0000,1294.0000,1366.0000,2.0,Index Points,Daily,2021-09-17T03:01:00
1,BEEF:COM,Beef,Beef,commodity,2021-09-16T00:00:00,20.410,20.410,2021-09-16T00:00:00,Livestock,/commodity/beef,...,12.5138,20.450,20.250,20.1700,16.6700,18.1400,2.0,BRL/Kg,Daily,2021-09-17T12:02:00
2,CHE:COM,CHEESE1,Cheese,commodity,2021-09-16T00:00:00,1.646,1.646,2021-09-16T00:00:00,Agricultural,/commodity/cheese,...,0.0000,1.649,1.654,1.5940,1.7560,1.6460,4.0,USD/Lbs,Daily,2021-09-17T01:16:00
3,CRYTR:IND,CRB,CRB Index,commodity,2021-09-16T00:00:00,238.016,238.016,2021-09-16T00:00:00,Index,/commodity/crb,...,33.4975,239.631,232.208,227.5916,160.1686,178.2925,2.0,Index Points,Daily,2021-09-17T12:02:00
4,DL1:COM,DL1,Ethanol,commodity,2021-09-16T00:00:00,2.207,2.207,2021-09-16T00:00:00,Energy,/commodity/ethanol,...,54.0126,2.207,2.207,2.2200,1.3450,1.4330,4.0,USD/Gal,Daily,2021-09-17T01:19:00
5,GAC:COM,GAC,Gallium,Commodity,2021-09-16T00:00:00,1925.000,1925.000,2021-09-16T00:00:00,Industrial,/commodity/gallium,...,10.6322,1925.000,1925.000,1925.0000,1250.0000,1740.0000,2.0,CNY/Kg,Daily,2021-09-17T12:02:00
6,GECNYBGQ:COM,GECNYBGQ,Germanium,Commodity,2021-09-16T00:00:00,8650.000,8650.000,2021-09-16T00:00:00,Industrial,/commodity/germanium,...,21.8310,8650.000,8650.000,8450.0000,6950.0000,7100.0000,2.0,CNY/Kg,Daily,2021-09-17T12:02:00
7,IMR:COM,IMR,Manganese,commodity,2021-09-16T00:00:00,34.500,34.500,2021-09-16T00:00:00,Industrial,/commodity/manganese,...,10.4000,34.500,34.500,32.7500,31.2500,31.2500,2.0,CNY/T,Daily,2021-09-17T12:02:00
8,IUC:COM,IUC,Indium,Commodity,2021-09-16T00:00:00,1700.000,1700.000,2021-09-16T00:00:00,Industrial,/commodity/indium,...,42.8571,1700.000,1800.000,1305.0000,1375.0000,1190.0000,2.0,CNY/Kg,Daily,2021-09-17T12:02:00
9,LCO1:COM,Cobalt,Cobalt,commodity,2021-09-16T00:00:00,51500.000,51500.000,2021-09-16T00:00:00,Industrial,/commodity/cobalt,...,59.9876,51500.000,51500.000,52300.0000,34200.0000,32190.0000,2.0,USD/T,Daily,2021-09-17T12:02:00

##### 2 Major Currencies
/markets/currency
https://api.tradingeconomics.com/markets/currency?c=guest:guest

In [3]:
te.getMarketsData(marketsField='currency', output_type='df')

,Symbol,Ticker,Name,Country,Date,Last,Close,CloseDate,Group,URL,...,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,decimals,unit,frequency,LastUpdate
0,AUDUSD:CUR,AUD,AUDUSD,australia,2021-09-17T14:42:00,0.72759,0.72759,2021-09-17T14:42:00,Australia G20 Major AUD Cross,/australia/currency,...,-5.6083,0.72910,0.73520,0.72350,0.72920,0.77080,5.0,,"Daily, Intraday, Live Stream",2021-09-17T14:42:00
1,BTCUSD:CUR,BTCUSD,BTCUSD,Other,2021-09-17T14:42:00,47402.87000,47402.87000,2021-09-17T14:42:00,Crypto,/btcusd:cur,...,63.4988,47760.64000,44857.38000,44721.13000,10933.68000,28992.79000,2.0,,"Daily, Intraday",2021-09-17T14:42:00
2,DXY:CUR,USD,DXY,United States,2021-09-17T14:43:00,93.10680,93.10680,2021-09-17T14:43:00,America G20 Major,/united-states/currency,...,3.5245,92.93200,92.58200,93.13600,92.92600,89.93700,3.0,,"Daily, Intraday",2021-09-17T14:43:00
3,EURUSD:CUR,EUR,EURUSD,euro area,2021-09-17T14:43:00,1.17443,1.17443,2021-09-17T14:43:00,Europe G20 Major EUR Cross,/euro-area/currency,...,-3.8668,1.17650,1.18100,1.17110,1.18410,1.22170,5.0,,"Daily, Intraday, Live Stream",2021-09-17T14:43:00
4,GBPUSD:CUR,GBP,GBPUSD,united kingdom,2021-09-17T14:42:00,1.37516,1.37516,2021-09-17T14:41:00,Europe G20 Major GBP Cross,/united-kingdom/currency,...,0.5726,1.37976,1.38307,1.37506,1.29177,1.36733,5.0,,"Daily, Intraday, Live Stream",2021-09-17T14:43:00
5,NZDUSD:CUR,NZD,NZDUSD,new zealand,2021-09-17T14:43:00,0.70340,0.70340,2021-09-17T14:43:00,Australia Major NZD Cross,/new-zealand/currency,...,-2.2336,0.70710,0.71110,0.68820,0.67600,0.71950,5.0,,"Daily, Intraday, Live Stream",2021-09-17T14:43:00
6,USDAED:CUR,AED,USDAED,united arab emirates,2021-09-17T14:40:00,3.67280,3.67280,2021-09-17T14:40:00,Asia,/united-arab-emirates/currency,...,0.0000,3.67280,3.67280,3.67280,3.67280,3.67280,4.0,,Daily,2021-09-17T14:41:00
7,USDAFN:CUR,USDAFN,USDAFN,afghanistan,2021-09-17T14:36:00,85.36000,85.36000,2021-09-17T14:36:00,Asia,/afghanistan/currency,...,10.8571,85.36000,84.58000,86.04000,76.75000,77.00000,2.0,,Daily,2021-09-17T14:40:00
8,USDALL:CUR,USDALL,USDALL,albania,2021-09-17T14:39:00,102.95000,102.95000,2021-09-17T14:39:00,Europe,/albania/currency,...,2.8472,102.84000,102.90000,103.35000,104.44000,100.10000,2.0,,"Daily, Intraday, Delayed Stream",2021-09-17T14:39:00
9,USDAMD:CUR,USDAMD,USDAMD,armenia,2021-09-17T14:26:00,489.00000,489.00000,2021-09-17T14:26:00,Asia,/armenia/currency,...,-5.8710,485.70000,491.85000,490.08000,484.25000,519.50000,2.0,,Daily,2021-09-17T14:31:00

##### 3 Currency Crosses
/markets/currency?cross=eur
https://api.tradingeconomics.com/markets/currency?c=guest:guest&cross=EUR

In [4]:
te.getCurrencyCross(cross='eur', output_type='df')

,Symbol,Ticker,Name,Country,Date,Last,Close,CloseDate,Group,URL,...,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,decimals,unit,frequency,LastUpdate
0,EURAED:CUR,EURAED,EURAED,Other,2021-09-17T00:00:00,4.325530,4.325530,2021-09-17T00:00:00,,/euraed:cur,...,-3.5975,4.320866,4.358678,4.332582,4.328615,4.486950,4.0,,Daily,2021-09-17T09:10:00
1,EURAFN:CUR,EURAFN,EURAFN,Other,2021-09-16T00:00:00,99.973570,99.973570,2021-09-16T00:00:00,,/eurafn:cur,...,6.2773,100.333189,102.382474,95.230897,90.806756,94.068590,2.0,,Daily,2021-09-16T12:53:00
2,EURALL:CUR,EURALL,EURALL,Other,2021-09-17T00:00:00,120.951844,120.951844,2021-09-17T00:00:00,,/eurall:cur,...,-1.0936,120.986118,121.600553,122.175315,123.242019,122.289167,2.0,,Daily,2021-09-17T09:10:00
3,EURAMD:CUR,EURAMD,EURAMD,Other,2021-09-17T00:00:00,576.847256,576.847256,2021-09-17T00:00:00,,/euramd:cur,...,-9.1089,571.401765,578.349554,578.440687,576.307142,634.657565,2.0,,Daily,2021-09-17T09:10:00
4,EURAOA:CUR,EURAOA,EURAOA,Other,2021-09-17T00:00:00,724.629724,724.629724,2021-09-17T00:00:00,,/euraoa:cur,...,-8.6910,725.869650,746.047511,752.867930,723.457779,793.601719,2.0,,Daily,2021-09-17T13:04:00
5,EURARS:CUR,EURARS,EURARS,Other,2021-09-13T00:00:00,115.950580,115.950580,2021-09-13T00:00:00,,/eurars:cur,...,12.8824,115.626582,116.241044,113.717747,88.636135,102.718014,4.0,,Daily,2021-09-13T21:30:00
6,EURAUD:CUR,EURAUD,EURAUD,Other,2021-09-17T14:43:00,1.614180,1.614180,2021-09-17T14:43:00,EUR Cross AUD Cross,/euraud:cur,...,1.8590,1.613200,1.605400,1.618600,1.623700,1.584700,4.0,,"Daily, Intraday, Live Stream",2021-09-17T14:43:00
7,EURAZN:CUR,EURAZN,EURAZN,Other,2021-09-17T00:00:00,1.993880,1.993880,2021-09-17T00:00:00,,/eurazn:cur,...,-3.5975,1.991730,2.009269,1.997131,1.995302,2.068287,4.0,,Daily,2021-09-17T09:10:00
8,EURBDT:CUR,EURBDT,EURBDT,Other,2021-09-16T00:00:00,100.276140,100.276140,2021-09-16T00:00:00,,/eurbdt:cur,...,-2.5974,100.155901,100.941793,99.020286,100.244235,102.950131,2.0,,Daily,2021-09-16T11:10:00
9,EURBGN:CUR,EURBGN,EURBGN,Other,2021-09-17T00:00:00,1.955369,1.955369,2021-09-17T00:00:00,,/eurbgn:cur,...,-0.0206,1.954907,1.955231,1.954744,1.955468,1.955772,4.0,,Daily,2021-09-17T09:10:00

##### 4 Stock Market Indexes
/markets/index
https://api.tradingeconomics.com/markets/index?c=guest:guest

In [5]:
te.getMarketsData(marketsField='index', output_type='df')

,Symbol,Ticker,Name,Country,Date,Last,Close,CloseDate,Group,URL,...,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,decimals,unit,frequency,LastUpdate
0,TA-100:IND,TA-25,TA-125,Israel,2021-01-05T15:14:00,1558.08,1558.08,2021-01-05T00:00:00,Asia,/israel/stock-market,...,-0.6384,1568.18,1547.72,1522.30,1617.15,1568.09,0.0,,"Daily, Intraday, Delayed Stream",2021-01-05T17:15:00
1,TA-125:IND,TA-25,TA-125,Israel,2021-09-14T14:14:00,1862.53,1862.53,2021-09-14T00:00:00,Asia,/israel/stock-market,...,18.7770,1856.68,1856.61,1772.83,1366.86,1568.09,0.0,,"Daily, Intraday, Delayed Stream",2021-09-17T14:32:00
2,TEDPIX:IND,TEDPIX,TEDPIX,Iran,2021-09-15T00:00:00,1488212.00,1488212.00,2021-09-15T00:00:00,Asia,/iran/stock-market,...,3.4110,1496962.00,1526008.00,1515548.00,1704108.00,1439124.00,2.0,,None,2021-09-17T03:01:00
3,BGSMDC:IND,BOTSWANASTOMAR,Gaborone,Botswana,2021-09-16T00:00:00,6848.31,6848.31,2021-09-16T00:00:00,Africa,/botswana/stock-market,...,-0.4512,6848.31,6742.79,6712.69,7008.82,6879.35,0.0,,Daily,2021-09-17T12:02:00
4,BSX:IND,BSX,BSX,Bermuda,2021-09-16T00:00:00,2568.92,2568.92,2021-09-16T00:00:00,America,/bermuda/stock-market,...,26.4319,2568.92,2567.50,2557.26,1806.93,2031.86,0.0,,Daily,2021-09-17T06:01:00
5,BVQA:IND,ECUADORSTOARKET,Ecuador General Index,Ecuador,2021-09-16T00:00:00,1262.59,1262.59,2021-09-16T00:00:00,America,/ecuador/stock-market,...,-9.3540,1263.34,1265.90,1289.09,1337.37,1392.88,0.0,,Daily,2021-09-17T12:02:00
6,CRSMBCT:IND,CRSMBCT,BCT Corp,Costa Rica,2021-09-16T00:00:00,11907.13,11907.13,2021-09-16T00:00:00,,/costa-rica/stock-market,...,54.8259,11907.13,11906.32,9812.54,7933.74,7690.66,0.0,,Daily,2021-09-17T14:01:00
7,DSM:IND,QATARSTOMAR,QE,Qatar,2021-09-16T00:00:00,11180.92,11180.92,2021-09-16T00:00:00,Asia,/qatar/stock-market,...,7.1384,11111.12,11100.32,10983.33,9942.06,10435.96,0.0,,"Daily, Intraday",2021-09-17T00:06:00
8,INDZI:IND,INDZI,Zimbabwe Industrial Index,Zimbabwe,2021-09-16T00:00:00,22734.73,22734.73,2021-09-16T00:00:00,Africa,/zimbabwe/stock-market,...,158.8734,22724.57,22273.92,22978.80,5473.24,8782.18,2.0,,Daily,2021-09-17T11:02:00
9,KNSMIDX:IND,KENYASTOMAR,Nairobi 20,Kenya,2021-09-16T00:00:00,2051.80,2051.80,2021-09-16T00:00:00,Africa,/kenya/stock-market,...,9.8165,2046.58,2062.22,1996.26,1844.60,1868.39,0.0,,Daily,2021-09-17T12:02:00

##### 5 Government Bonds
/markets/bond
https://api.tradingeconomics.com/markets/bond?c=guest:guest

In [7]:
te.getMarketsData(marketsField='bond', output_type='df')

,Symbol,Ticker,Name,Country,Date,Last,Close,CloseDate,Group,URL,...,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,decimals,unit,frequency,LastUpdate
0,GISR10YR:GOV,GISR10YR,Israel 10Y,israel,2021-09-14T13:27:00,1.055,1.055,2021-09-14T13:27:00,Asia 10Y,/israel/government-bond-yield,...,0.281,1.056,1.055,1.003,0.725,0.774,4.0,percent,Daily,2021-09-14T13:27:00
1,GMXN10YR:IND,GMXN10YR,Mexico 10Y,mexico,2021-09-15T18:37:00,7.003,7.003,2021-09-15T18:37:00,America G20 Major 10Y,/mexico/government-bond-yield,...,1.703,6.998,6.978,7.058,5.650,5.300,4.0,percent,Daily,2021-09-17T00:05:00
2,BGRGOVB10Y:GOV,BULGARIAGOVBON10Y,Bulgaria 10Y,bulgaria,2021-09-16T00:00:00,0.300,0.300,2021-09-16T00:00:00,Europe 10Y,/bulgaria/government-bond-yield,...,-0.100,0.300,0.400,0.400,0.400,0.400,4.0,percent,Daily,2021-09-16T11:06:00
3,CHLGOVBON10Y:GOV,CHILEGOVBON10Y,Chile 10Y,chile,2021-09-16T00:00:00,5.310,5.310,2021-09-16T00:00:00,America 10Y,/chile/government-bond-yield,...,2.200,5.320,2.830,2.820,3.400,3.110,4.0,percent,Daily,2021-09-16T21:02:00
4,LTUGOVBON10Y:GOV,LITHUANIAGOVBON10Y,Lithuania 10Y,Lithuania,2021-09-16T00:00:00,0.069,0.069,2021-09-16T00:00:00,Europe 10Y,/lithuania/government-bond-yield,...,-0.356,0.059,0.066,0.127,0.400,0.425,4.0,percent,Daily,2021-09-16T15:26:00
5,LVAGOVBON10Y:GOV,LATVIAGOVBON10Y,Latvia 10Y,latvia,2021-09-16T00:00:00,0.549,0.549,2021-09-16T00:00:00,Europe 10Y,/latvia/government-bond-yield,...,0.000,0.549,0.549,0.549,0.549,0.549,4.0,percent,Daily,2021-09-17T12:02:00
6,NGAGOVBON10Y:GOV,NIGERIAGOVBON10Y,Nigeria 10Y,nigeria,2021-09-16T00:00:00,11.942,11.942,2021-09-16T00:00:00,Africa 10Y,/nigeria/government-bond-yield,...,0.380,12.066,4.734,4.852,12.705,11.562,4.0,percent,Daily,2021-09-16T15:31:00
7,RUGE1M:GOV,RUGE1M,Russia 1M,Russia,2021-09-16T00:00:00,6.650,6.650,2021-09-16T00:00:00,Europe 1M,/russia/1-month-bill-yield,...,2.470,6.650,6.780,6.400,4.160,4.180,4.0,percent,Daily,2021-09-17T01:13:00
8,RUGE3M:GOV,RUGE3M,Russia 3M,Russia,2021-09-16T00:00:00,6.850,6.850,2021-09-16T00:00:00,Europe 3M,/russia/3-month-bill-yield,...,2.640,6.830,6.930,6.590,4.170,4.210,4.0,percent,Daily,2021-09-17T01:13:00
9,RUGE6M:GOV,RUGE6M,Russia 6M,Russia,2021-09-16T00:00:00,7.070,7.070,2021-09-16T00:00:00,Europe 6M,/russia/6-month-bill-yield,...,2.830,7.030,7.100,6.790,4.190,4.240,4.0,percent,Daily,2021-09-17T01:13:00

##### 6  Individual Market (stock, index, currency, commodity or bond)
/markets/symbol/{symbol}
https://api.tradingeconomics.com/markets/symbol/aapl:us?c=guest:guest

In [8]:
te.getMarketsBySymbol(symbols='aapl:us', output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,Close,CloseDate,...,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,frequency,LastUpdate
0,AAPL:US,AAPL,Apple,United States,2021-09-17T14:46:00,stocks,2.0,146.82,146.82,2021-09-17T14:46:00,...,14.13,10.6489,148.79,148.97,146.36,106.84,132.69,US0378331005,"Daily, Intraday, Live Stream",2021-09-17T14:46:00

##### 7 Multiple Markets
/markets/symbol/{symbols}
https://api.tradingeconomics.com/markets/symbol/aapl:us,indu:ind?c=guest:guest

In [9]:
te.getMarketsBySymbol(symbols=['aapl:us','indu:ind'], output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,Close,CloseDate,...,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,frequency,LastUpdate
0,AAPL:US,AAPL,Apple,United States,2021-09-17T14:46:00,stocks,2.0,146.82000,146.82000,2021-09-17T14:46:00,...,14.13000,10.6489,148.79,148.97,146.36,106.84,132.69,US0378331005,"Daily, Intraday, Live Stream",2021-09-17T14:46:00
1,INDU:IND,INDU,US30,United States,2021-09-17T14:46:00,index,0.0,34427.78906,34427.78906,2021-09-17T14:44:00,...,3821.30906,12.4853,34751.32,34607.72,34960.69,27657.42,30606.48,None,"Daily, Intraday, Live Stream",2021-09-17T14:46:00

##### 8 List of stocks by country
/markets/country/{country}
https://api.tradingeconomics.com/markets/country/united%20states?client=guest:guest

In [10]:
te.getMarketsSearch(country='united states', output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,Close,CloseDate,...,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,frequency,LastUpdate
0,SPX:IND,SPX,US500,United States,2021-09-17T14:49:00,index,2.0,4430.7700,4430.7700,2021-09-17T14:49:00,...,674.7000,17.9629,4473.7500,4458.5800,4400.2700,3319.4700,3756.070,None,"Daily, Intraday, Live Stream",None
1,USGG10YR:IND,USGG10YR,US 10Y,united states,2021-09-17T14:48:00,bond,4.0,1.3804,1.3804,2021-09-17T14:48:00,...,0.4684,0.4684,1.3361,1.3428,1.2600,0.6953,0.912,None,Daily,None
2,USGG12M:IND,UNITEDSTA52WEEBILYIE,US 52W,united states,2021-09-17T10:13:00,bond,4.0,0.0735,0.0735,2021-09-17T10:13:00,...,-0.0385,-0.0385,0.0710,0.0710,0.0680,0.1167,0.112,None,Daily,None
3,USGG1M:IND,UNITEDSTA4WEEBILYIE,US 1M,united states,2021-09-17T12:14:00,bond,4.0,0.0532,0.0532,2021-09-17T12:12:00,...,-0.0028,-0.0002,0.0410,0.0530,0.0330,0.0761,0.056,None,Daily,None
4,USGG2YR:IND,UNITEDSTA2YEANOTYIE,US 2Y,united states,2021-09-17T14:48:00,bond,4.0,0.2277,0.2277,2021-09-17T14:48:00,...,0.1067,0.1067,0.2213,0.2147,0.2175,0.1391,0.121,None,Daily,None
5,USGG3M:IND,UNITEDSTA3MONBILYIE,US 3M,united states,2021-09-17T13:35:00,bond,4.0,0.0355,0.0355,2021-09-17T13:35:00,...,-0.0435,-0.0435,0.0380,0.0480,0.0610,0.0811,0.079,None,Daily,None
6,USGG3Y:IND,UNITEDSTA3YEANOTYIE,US 3Y,united states,2021-09-17T14:49:00,bond,4.0,0.4779,0.4779,2021-09-17T14:49:00,...,0.3129,0.3129,0.4592,0.4458,0.4276,0.1644,0.165,None,Daily,None
7,USGG5YR:IND,UNITEDSTA5YEANOTYIE,US 5Y,united states,2021-09-17T14:48:00,bond,4.0,0.8729,0.8729,2021-09-17T14:48:00,...,0.5139,0.5139,0.8404,0.8160,0.7685,0.2818,0.359,None,Daily,None
8,USGG6M:IND,UNITEDSTA6MONBILYIE,US 6M,united states,2021-09-17T10:48:00,bond,4.0,0.0456,0.0456,2021-09-17T10:48:00,...,-0.0434,-0.0434,0.0460,0.0510,0.0510,0.1040,0.089,None,Daily,None
9,USGG7Y:IND,UNITEDSTA7YEANOTYIE,US 7Y,united states,2021-09-17T14:48:00,bond,4.0,1.1755,1.1755,2021-09-17T14:48:00,...,0.5335,0.5335,1.1344,1.1226,1.0420,0.4771,0.642,None,Daily,None

##### 9 A snapshot of latest peers prices by market
/markets/peers/{symbol}
https://api.tradingeconomics.com/markets/peers/aapl:us?c=guest:guest

In [11]:
te.getMarketsPeers(symbols='aapl:us', output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,Close,CloseDate,...,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,frequency,LastUpdate
0,6758:JP,6758,Sony,Japan,2021-09-17T00:00:00,stocks,2.0,12195.0000,12195.0000,2021-09-17T00:00:00,...,1910.0000,18.5707,12270.0000,12235.0000,10900.0000,8323.0000,10285.0000,JP3435000009,"Daily, Intraday",2021-09-17T07:02:00
1,AAPL:US,AAPL,Apple,United States,2021-09-17T14:49:00,stocks,2.0,146.7200,146.7200,2021-09-17T14:49:00,...,14.0300,10.5735,148.7900,148.9700,146.3600,106.8400,132.6900,US0378331005,"Daily, Intraday, Live Stream",2021-09-17T14:49:00
2,ADI:US,ADI:US,Analog Devices,United States,2021-09-17T14:49:00,stocks,2.0,171.1800,171.1800,2021-09-17T14:49:00,...,23.4500,15.8736,173.2100,169.9400,165.7800,114.9100,147.7300,US0326541051,"Daily, Intraday, Live Stream",2021-09-17T14:49:00
3,AMAT:US,AMAT,Applied Materials,United States,2021-09-17T14:49:00,stocks,2.0,141.3800,141.3800,2021-09-17T14:49:00,...,55.0800,63.8239,144.0900,136.8400,127.3700,56.1500,86.3000,US0382221051,"Daily, Intraday, Live Stream",2021-09-17T14:49:00
4,AMD:US,AMD,Advanced Micro Devices,United States,2021-09-17T14:49:00,stocks,2.0,104.9700,104.9700,2021-09-17T14:49:00,...,13.2600,14.4586,106.2200,105.2000,103.4400,74.9300,91.7100,US0079031078,"Daily, Intraday, Live Stream",2021-09-17T14:49:00
5,AMZN:US,AMZN,Amazon,United States,2021-09-17T14:49:00,stocks,2.0,3479.0000,3479.0000,2021-09-17T14:49:00,...,222.0700,6.8184,3488.2400,3469.1500,3201.2200,2954.9100,3256.9300,US0231351067,"Daily, Intraday, Live Stream",2021-09-17T14:49:00
6,ANET:US,ANET,Arista Networks,United States,2021-09-17T14:46:00,stocks,2.0,358.0900,358.0900,2021-09-17T14:46:00,...,67.5200,23.2371,364.9300,350.9200,362.0700,200.9800,290.5700,US0404131064,"Daily, Intraday, Live Stream",2021-09-17T14:46:00
7,APH:US,APH,Amphenol,United States,2021-09-17T14:49:00,stocks,2.0,75.7300,75.7300,2021-09-17T14:49:00,...,-55.0400,-42.0892,76.4700,75.3600,73.9100,108.8700,130.7700,US0320951017,"Daily, Intraday, Live Stream",2021-09-17T14:49:00
8,AVGO:US,AVGO,Avago Technologies,Singapore,2021-09-17T14:49:00,stocks,2.0,502.4300,502.4300,2021-09-17T14:49:00,...,64.5800,14.7493,507.3500,498.1500,468.9700,359.7300,437.8500,SG9999014823,"Daily, Intraday, Live Stream",2021-09-17T14:49:00
9,CCMP:IND,CCMP,NASDAQ,United States,2021-09-17T14:29:00,index,0.0,15088.9736,15088.9736,2021-09-17T14:29:00,...,2200.6914,17.0751,15181.9238,15115.4941,14525.9141,10793.2822,12888.2822,None,"Daily, Intraday, Delayed Stream",2021-09-17T14:45:00
10,INDU:IND,INDU,US30,United States,2021-09-17T14:49:00,index,0.0,34451.7900,34451.7900,2021-09-17T14:49:00,...,3845.3100,12.5637,34751.3200,34607.7200,34960.6900,27657.4200,30606.4800,None,"Daily, Intraday, Live Stream",2021-09-17T14:49:00
11,NDX:IND,NDX,USNDX,United States,2021-09-17T14:49:00,index,0.0,15350.9200,15350.9200,2021-09-17T14:49:00,...,2462.6358,19.1076,15515.9072,15440.7480,14857.9238,10936.9824,12888.2842,None,"Daily, Intraday, Live Stream",2021-09-17T14:49:00
12,SPX:IND,SPX,US500,United States,2021-09-17T14:49:00,index,2.0,4430.7700,4430.7700,2021-09-17T14:49:00,...,674.7000,17.9629,4473.7500,4458.5800,4400.2700,3319.4700,3756.0700,None,"Daily, Intraday, Live Stream",2021-09-17T14:49:00

##### 10 Stock Market Index Components
/markets/components/{symbol}
https://api.tradingeconomics.com/markets/components/psi20:ind?c=guest:guest

In [13]:
te.getMarketsComponents(symbols=['psi20:ind'], output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,Close,CloseDate,...,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,frequency,LastUpdate
0,ALTR:PL,ALTR,Altri,Portugal,2021-09-17T00:00:00,stocks,2.0,5.4900,5.4900,2021-09-17T00:00:00,...,0.3300,6.3953,5.4900,5.5050,5.2350,4.2400,5.1600,PTALT0AE0002,Daily,2021-09-17T08:02:00
1,BCP:PL,BCP:PL,BCP,Portugal,2021-09-17T00:00:00,stocks,2.0,0.1315,0.1315,2021-09-17T00:00:00,...,0.0083,6.7370,0.1305,0.1257,0.1267,0.0907,0.1232,PTBCP0AM0007,Daily,2021-09-17T08:03:00
2,COR:PL,COR:PL,Corticeira Amorim,Portugal,2021-09-17T14:48:00,stocks,2.0,11.5400,11.5400,2021-09-17T14:48:00,...,-0.0600,-0.5172,11.7000,11.7200,11.5000,11.0200,11.6000,PTCOR0AE0006,Daily,2021-09-17T14:48:00
3,CTT:PL,CTT:PL,CTT,Portugal,2021-09-17T00:00:00,stocks,2.0,4.8200,4.8200,2021-09-17T00:00:00,...,2.4700,105.1064,4.7700,4.6200,4.5050,2.5150,2.3500,PTCTT0AM0001,Daily,2021-09-17T08:16:00
4,EDP:PL,EDP,EDP,Portugal,2021-09-17T14:48:00,stocks,2.0,4.6470,4.6470,2021-09-17T14:48:00,...,-0.5090,-9.8720,4.6400,4.6690,4.6490,4.2180,5.1560,PTEDP0AM0009,Daily,2021-09-17T14:48:00
5,EDPR:PL,EDPR,EDP Renovaveis,Spain,2021-09-17T14:47:00,stocks,2.0,21.7800,21.7800,2021-09-17T14:47:00,...,-1.0200,-4.4737,21.7200,21.9400,21.7000,14.3400,22.8000,ES0127797019,Daily,2021-09-17T14:47:00
6,EGL:PL,EGL:PL,Mota Engil,Portugal,2021-09-17T00:00:00,stocks,2.0,1.3900,1.3900,2021-09-17T00:00:00,...,0.0260,1.9062,1.3900,1.3560,1.3400,1.2700,1.3640,PTMEN0AE0005,Daily,2021-09-17T08:02:00
7,GALP:PL,GALP,Galp,Portugal,2021-09-17T00:00:00,stocks,2.0,8.3800,8.3800,2021-09-17T00:00:00,...,-0.3740,-4.2723,8.4040,8.2120,8.6100,8.7120,8.7540,PTGAL0AM0009,Daily,2021-09-17T08:06:00
8,IBS:PL,IBS,Ibersol,Portugal,2021-09-17T00:00:00,stocks,2.0,5.7200,5.7200,2021-09-17T00:00:00,...,0.3200,5.9259,5.6800,5.8000,5.9600,5.3200,5.4000,PTIBS0AM0008,Daily,2021-09-17T08:03:00
9,JMT:PL,JMT,Jeronimo Martins,Portugal,2021-09-17T00:00:00,stocks,2.0,17.7400,17.7400,2021-09-17T00:00:00,...,3.9200,28.3647,17.7150,17.6800,17.9500,14.1650,13.8200,PTJMT0AE0001,Daily,2021-09-17T08:04:00

## Search

##### 11 Search method
/markets/search/{term}
https://api.tradingeconomics.com/markets/search/united%20states?c=guest:guest

In [14]:
te.getMarketsSearch(country='united states', output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,Close,CloseDate,...,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,frequency,LastUpdate
0,SPX:IND,SPX,US500,United States,2021-09-17T14:49:00,index,2.0,4430.7700,4430.7700,2021-09-17T14:49:00,...,674.7000,17.9629,4473.7500,4458.5800,4400.2700,3319.4700,3756.070,None,"Daily, Intraday, Live Stream",None
1,USGG10YR:IND,USGG10YR,US 10Y,united states,2021-09-17T14:48:00,bond,4.0,1.3804,1.3804,2021-09-17T14:48:00,...,0.4684,0.4684,1.3361,1.3428,1.2600,0.6953,0.912,None,Daily,None
2,USGG12M:IND,UNITEDSTA52WEEBILYIE,US 52W,united states,2021-09-17T10:13:00,bond,4.0,0.0735,0.0735,2021-09-17T10:13:00,...,-0.0385,-0.0385,0.0710,0.0710,0.0680,0.1167,0.112,None,Daily,None
3,USGG1M:IND,UNITEDSTA4WEEBILYIE,US 1M,united states,2021-09-17T12:14:00,bond,4.0,0.0532,0.0532,2021-09-17T12:12:00,...,-0.0028,-0.0002,0.0410,0.0530,0.0330,0.0761,0.056,None,Daily,None
4,USGG2YR:IND,UNITEDSTA2YEANOTYIE,US 2Y,united states,2021-09-17T14:48:00,bond,4.0,0.2277,0.2277,2021-09-17T14:48:00,...,0.1067,0.1067,0.2213,0.2147,0.2175,0.1391,0.121,None,Daily,None
5,USGG3M:IND,UNITEDSTA3MONBILYIE,US 3M,united states,2021-09-17T13:35:00,bond,4.0,0.0355,0.0355,2021-09-17T13:35:00,...,-0.0435,-0.0435,0.0380,0.0480,0.0610,0.0811,0.079,None,Daily,None
6,USGG3Y:IND,UNITEDSTA3YEANOTYIE,US 3Y,united states,2021-09-17T14:49:00,bond,4.0,0.4779,0.4779,2021-09-17T14:49:00,...,0.3129,0.3129,0.4592,0.4458,0.4276,0.1644,0.165,None,Daily,None
7,USGG5YR:IND,UNITEDSTA5YEANOTYIE,US 5Y,united states,2021-09-17T14:48:00,bond,4.0,0.8729,0.8729,2021-09-17T14:48:00,...,0.5139,0.5139,0.8404,0.8160,0.7685,0.2818,0.359,None,Daily,None
8,USGG6M:IND,UNITEDSTA6MONBILYIE,US 6M,united states,2021-09-17T10:48:00,bond,4.0,0.0456,0.0456,2021-09-17T10:48:00,...,-0.0434,-0.0434,0.0460,0.0510,0.0510,0.1040,0.089,None,Daily,None
9,USGG7Y:IND,UNITEDSTA7YEANOTYIE,US 7Y,united states,2021-09-17T14:48:00,bond,4.0,1.1755,1.1755,2021-09-17T14:48:00,...,0.5335,0.5335,1.1344,1.1226,1.0420,0.4771,0.642,None,Daily,None

##### 12 Filtering by Category
/markets/search/{term}?category={category}
https://api.tradingeconomics.com/markets/search/united%20states?c=guest:guest&category=index,markets

In [15]:
te.getMarketsSearch(country='united states', category=['index','markets'], output_type='df')

,Symbol,Ticker,Name,Country,Date,Type,decimals,Last,Close,CloseDate,...,YTDChange,YTDPercentualChange,yesterday,lastWeek,lastMonth,lastYear,startYear,ISIN,frequency,LastUpdate
0,CCMP:IND,CCMP,NASDAQ,United States,2021-09-17T14:29:00,index,0.0,15088.9736,15088.9736,2021-09-17T14:29:00,...,2200.6914,17.0751,15181.9238,15115.4941,14525.9141,10793.2822,12888.2822,None,"Daily, Intraday, Delayed Stream",None
1,INDU:IND,INDU,US30,United States,2021-09-17T14:49:00,index,0.0,34451.7900,34451.7900,2021-09-17T14:49:00,...,3845.3100,12.5637,34751.3200,34607.7200,34960.6900,27657.4200,30606.4800,None,"Daily, Intraday, Live Stream",None
2,MID:IND,MID,US400,United States,2021-09-17T14:33:00,index,0.0,2681.8400,2681.8400,2021-09-17T14:33:00,...,375.2200,16.2671,2697.3000,2686.5300,2667.0700,1865.8600,2306.6200,None,"Daily, Intraday, Delayed Stream",None
3,NDX:IND,NDX,USNDX,United States,2021-09-17T14:49:00,index,0.0,15350.9200,15350.9200,2021-09-17T14:49:00,...,2462.6358,19.1076,15515.9072,15440.7480,14857.9238,10936.9824,12888.2842,None,"Daily, Intraday, Live Stream",None
4,SPX:IND,SPX,US500,United States,2021-09-17T14:49:00,index,2.0,4430.7700,4430.7700,2021-09-17T14:49:00,...,674.7000,17.9629,4473.7500,4458.5800,4400.2700,3319.4700,3756.0700,None,"Daily, Intraday, Live Stream",None
5,USM:US,USM,United States Cellular,United States,2021-09-17T14:49:00,stocks,2.0,31.0400,31.0400,2021-09-17T14:49:00,...,0.3500,1.1404,30.8500,31.3100,31.1500,32.0000,30.6900,None,"Daily, Intraday, Live Stream",None
6,USO:US,USO,United States Oil Fund,United States,2021-09-17T14:49:00,stocks,2.0,50.0200,50.0200,2021-09-17T14:49:00,...,17.0100,51.5298,50.7000,48.8000,45.4000,29.1200,33.0100,None,"Daily, Intraday, Live Stream",None
7,VIX:IND,VIX,USVIX,United States,2021-09-17T14:29:00,index,2.0,19.6300,19.6300,2021-09-17T14:29:00,...,-3.1200,-3.1200,18.6900,20.9500,21.5700,25.8300,22.7500,None,"Daily, Intraday, Delayed Stream",None
8,W5000:IND,W5000,US5000,United States,2021-09-17T14:33:00,index,2.0,46249.6300,46249.6300,2021-09-17T14:33:00,...,6792.9700,17.2163,46491.2700,46344.4800,45556.4900,34055.1800,39456.6600,None,Daily,None
9,X:US,X:US,United States Steel,United States,2021-09-17T14:48:00,stocks,2.0,23.5400,23.5400,2021-09-17T14:48:00,...,6.7700,40.3697,25.3900,25.9200,29.4500,8.8200,16.7700,None,"Daily, Intraday, Live Stream",None

## Historical

##### 13 - Historical Data for 1 instrument
/markets/historical/{symbol}
https://api.tradingeconomics.com/markets/historical/aapl:us?c=guest:guest

In [19]:
te.fetchMarkets(symbol='aapl:us', output_type='df')

             symbol    open    high        low   close
2021-09-17  AAPL:US  148.82  148.82  146.64999  146.69
2021-09-16  AAPL:US  148.44  148.97  147.22100  148.79
2021-09-15  AAPL:US  148.56  149.44  146.37000  149.03
2021-09-14  AAPL:US  150.35  151.07  146.91000  148.12
2021-09-13  AAPL:US  150.63  151.42  148.75000  149.55
2021-09-10  AAPL:US  155.00  155.48  148.70000  148.97
2021-09-09  AAPL:US  155.49  156.11  153.95000  154.07
2021-09-08  AAPL:US  156.98  157.04  153.97500  155.11
2021-09-07  AAPL:US  154.97  157.26  154.39000  156.69
2021-09-03  AAPL:US  153.76  154.63  153.09000  154.30

##### 13 Historical Data for multiple instruments
/markets/historical/{symbols}
https://api.tradingeconomics.com/markets/historical/aapl:us,indu:ind?c=guest:guest

In [20]:
te.fetchMarkets(symbol=['aapl:us','indu:ind'], output_type='df')

              symbol      open      high          low        close
2021-09-17  INDU:IND  34737.86  34779.86  34418.78906  34421.78906
2021-09-17   AAPL:US    148.82    148.82    146.64999    146.69000
2021-09-16   AAPL:US    148.44    148.97    147.22100    148.79000
2021-09-16  INDU:IND  34810.27  34943.55  34540.11000  34751.32000
2021-09-15  INDU:IND  34580.95  34880.77  34522.03000  34814.39000
2021-09-15   AAPL:US    148.56    149.44    146.37000    149.03000
2021-09-14   AAPL:US    150.35    151.07    146.91000    148.12000
2021-09-14  INDU:IND  34906.90  34990.36  34510.30000  34577.57000
2021-09-13  INDU:IND  34665.50  34939.10  34665.50000  34869.63000
2021-09-13   AAPL:US    150.63    151.42    148.75000    149.55000

##### 14 Filter historical data by date
/markets/historical/{symbol}?d1=yyyy-mm-dd&d2=yyyy-mm-dd
https://api.tradingeconomics.com/markets/historical/aapl:us?c=guest:guest&d1=2017-08-01&d2=2017-08-08

In [21]:
te.fetchMarkets(symbol=['aapl:us','indu:ind'], initDate = '2017-01-01', endDate = '2017-06-15',output_type='df')

              symbol      open      high          low        close
2021-09-17  INDU:IND  34737.86  34779.86  34418.78906  34445.78906
2021-09-17   AAPL:US    148.82    148.82    146.64999    146.69000
2021-09-16   AAPL:US    148.44    148.97    147.22100    148.79000
2021-09-16  INDU:IND  34810.27  34943.55  34540.11000  34751.32000
2021-09-15  INDU:IND  34580.95  34880.77  34522.03000  34814.39000
2021-09-15   AAPL:US    148.56    149.44    146.37000    149.03000
2021-09-14   AAPL:US    150.35    151.07    146.91000    148.12000
2021-09-14  INDU:IND  34906.90  34990.36  34510.30000  34577.57000
2021-09-13  INDU:IND  34665.50  34939.10  34665.50000  34869.63000
2021-09-13   AAPL:US    150.63    151.42    148.75000    149.55000

## Intraday

##### 15 Intraday prices for a single instrument
/markets/intraday/{symbol}
https://api.tradingeconomics.com/markets/intraday/aapl:us?c=guest:guest

In [22]:
te.getMarketsIntraday(symbols='aapl:us', output_type='df')

      Symbol                 Date       Open       High        Low      Close
0    AAPL:US  2021-09-17T14:54:00  146.78000  146.78999  146.77000  146.78999
1    AAPL:US  2021-09-17T14:53:00  146.63000  146.75000  146.63000  146.75000
2    AAPL:US  2021-09-17T14:52:00  146.67999  146.72000  146.63000  146.63000
3    AAPL:US  2021-09-17T14:51:00  146.62000  146.64999  146.60001  146.64999
4    AAPL:US  2021-09-17T14:49:00  146.70000  146.73000  146.67999  146.72000
..       ...                  ...        ...        ...        ...        ...
995  AAPL:US  2021-09-14T17:23:00  148.88000  148.88000  148.77000  148.77000
996  AAPL:US  2021-09-14T17:22:00  148.77000  148.88000  148.77000  148.86000
997  AAPL:US  2021-09-14T17:21:00  148.78000  148.80000  148.75999  148.78000
998  AAPL:US  2021-09-14T17:20:00  148.78999  148.78999  148.77000  148.78000
999  AAPL:US  2021-09-14T17:19:00  148.75999  148.84000  148.74001  148.78999

[1000 rows x 6 columns]

##### Filter 16 intraday prices by date and hour
/markets/intraday/{symbol}?d1=yyyy-mm-dd hh:mm
https://api.tradingeconomics.com/markets/intraday/aapl:us?c=guest:guest&d1=2017-08-10%2015:30

In [23]:
te.getMarketsIntraday(symbols = 'indu:ind', initDate='2018-03-13 15:30', output_type='df')

,Symbol,Date,Open,High,Low,Close
0,INDU:IND,2021-09-17T14:53:00,34423.78906,34450.78906,34418.78906,34448.78906
1,INDU:IND,2021-09-17T14:52:00,34424.78906,34433.78906,34418.78906,34422.78906
2,INDU:IND,2021-09-17T14:51:00,34417.78906,34429.78906,34414.78906,34422.78906
3,INDU:IND,2021-09-17T14:50:00,34443.78906,34443.78906,34413.78906,34418.78906
4,INDU:IND,2021-09-17T14:49:00,34450.78906,34450.78906,34435.78906,34442.78906
5,INDU:IND,2021-09-17T14:48:00,34426.78906,34451.78906,34424.78906,34450.78906
6,INDU:IND,2021-09-17T14:47:00,34416.78906,34425.78906,34409.78125,34424.78906
7,INDU:IND,2021-09-17T14:46:00,34421.78906,34426.78906,34411.78125,34418.78906
8,INDU:IND,2021-09-17T14:45:00,34423.78906,34428.78906,34416.78906,34420.78906
9,INDU:IND,2021-09-17T14:44:00,34438.78906,34443.78906,34425.78906,34425.78906

##### 17 Filter intraday prices by date
/markets/intraday/{symbol}?d1=yyyy-mm-dd&d2=yyyy-mm-dd
https://api.tradingeconomics.com/markets/intraday/aapl:us?c=guest:guest&d1=2017-08-01&d2=2017-08-08

In [24]:
te.getMarketsIntraday(symbols = ['aapl:us', 'indu:ind'], initDate='2018-03-13', endDate='2018-04-01', output_type = 'df')

,Symbol,Date,Open,High,Low,Close
0,AAPL:US,2021-09-17T14:55:00,146.84000,146.87000,146.83000,146.87000
1,INDU:IND,2021-09-17T14:55:00,34451.78906,34453.78906,34429.78906,34430.78906
2,AAPL:US,2021-09-17T14:54:00,146.78000,146.85001,146.77000,146.85001
3,INDU:IND,2021-09-17T14:54:00,34451.78906,34459.78906,34437.78906,34454.78906
4,AAPL:US,2021-09-17T14:53:00,146.63000,146.75000,146.63000,146.75000
5,INDU:IND,2021-09-17T14:53:00,34423.78906,34450.78906,34418.78906,34448.78906
6,AAPL:US,2021-09-17T14:52:00,146.67999,146.72000,146.63000,146.63000
7,INDU:IND,2021-09-17T14:52:00,34424.78906,34433.78906,34418.78906,34422.78906
8,AAPL:US,2021-09-17T14:51:00,146.62000,146.64999,146.60001,146.64999
9,INDU:IND,2021-09-17T14:51:00,34417.78906,34429.78906,34414.78906,34422.78906

##### 18 Aggregate intraday prices by interval - allowed intervals: 1m, 5m, 10m, 15m, 30m, 1h, 2h, 4h
/markets/intraday/{symbol}?agr={interval}&d1=yyyy-mm-dd&d2=yyyy-mm-dd

http://api.tradingeconomics.com//markets/intraday/CL1:COM?agr=1m&d1=2021-01-01%2000:00&d2=2021-12-01%2015:30&client=guest:guest

In [2]:
te.getMarketsIntradayByInterval(symbol='CL1:COM',interval='1m',initDate='2021-01-01',endDate='2021-12-01',output_type='df')

    Symbol                 Date   Open   High    Low  Close
0  CL1:COM  2021-09-21T13:37:00  70.74  70.74  70.67  70.69
1  CL1:COM  2021-09-21T13:36:00  70.78  70.82  70.72  70.75
2  CL1:COM  2021-09-21T13:35:00  70.82  70.85  70.78  70.79
3  CL1:COM  2021-09-21T13:34:00  70.84  70.86  70.79  70.81
4  CL1:COM  2021-09-21T13:33:00  70.77  70.87  70.71  70.83
5  CL1:COM  2021-09-21T13:32:00  70.77  70.82  70.58  70.76
6  CL1:COM  2021-09-21T13:31:00  70.78  70.83  70.73  70.76
7  CL1:COM  2021-09-21T13:30:00  70.84  70.84  70.75  70.79
8  CL1:COM  2021-09-21T13:29:00  70.77  70.87  70.77  70.85

## Forecasts

##### 19  Market forecasts for major stock market indexes
/markets/forecasts/index
http://api.tradingeconomics.com/markets/forecasts/index?c=guest:guest

In [28]:
te.getMarketsForecasts(category = 'index', output_type='df')

,Symbol,Country,Date,Type,Last,Url,Importance,Forecast1,Forecast2,Forecast3,Forecast4
0,TA-125:IND,Israel,2021-09-14T14:14:00,index,1862.53,NaN,400,1.811290e+03,1.768244e+03,1.726125e+03,1.684934e+03
1,TEDPIX:IND,Iran,2021-09-15T00:00:00,index,1488212.00,NaN,1000,1.464957e+06,1.402208e+06,1.342214e+06,1.284822e+06
2,BGSMDC:IND,Botswana,2021-09-16T00:00:00,index,6848.31,NaN,999,6.709088e+03,6.677407e+03,6.646399e+03,6.614718e+03
3,BSX:IND,Bermuda,2021-09-16T00:00:00,index,2568.92,NaN,999,2.433795e+03,2.305863e+03,2.184610e+03,2.069522e+03
4,BVQA:IND,Ecuador,2021-09-16T00:00:00,index,1262.59,NaN,66,1.253389e+03,1.242005e+03,1.230621e+03,1.219490e+03
5,CRSMBCT:IND,Costa Rica,2021-09-16T00:00:00,index,11907.13,NaN,1000,1.090336e+04,9.984129e+03,9.142294e+03,8.371903e+03
6,DSM:IND,Qatar,2021-09-16T00:00:00,index,11180.92,NaN,530,1.091938e+04,1.074178e+04,1.056639e+04,1.039434e+04
7,INDZI:IND,Zimbabwe,2021-09-16T00:00:00,index,22734.73,NaN,1000,1.786146e+04,1.432213e+04,1.148666e+04,9.210266e+03
8,KNSMIDX:IND,Kenya,2021-09-16T00:00:00,index,2051.80,NaN,780,2.037028e+03,2.011029e+03,1.985236e+03,1.959855e+03
9,MONEX:IND,Montenegro,2021-09-16T00:00:00,index,10992.60,NaN,1000,1.086425e+04,1.068979e+04,1.051753e+04,1.034749e+04

##### 20 Market forecasts for major exchange rates
/markets/forecasts/currency
http://api.tradingeconomics.com/markets/forecasts/currency?c=guest:guest

In [29]:
te.getMarketsForecasts(category = 'currency', output_type='df')

,Symbol,Country,Date,Type,Last,Url,Importance,Forecast1,Forecast2,Forecast3,Forecast4
0,AUDUSD:CUR,australia,2021-09-17T14:58:00,currency,0.72702,NaN,3,0.729716,0.724572,0.719501,0.714504
1,BTCUSD:CUR,Other,2021-09-17T14:57:00,currency,47520.89000,NaN,4,43397.127110,41033.384762,38793.521482,36682.170998
2,DXY:CUR,United States,2021-09-17T14:57:00,currency,93.14153,NaN,13,96.060816,96.481632,96.912012,97.332828
3,EURUSD:CUR,euro area,2021-09-17T14:58:00,currency,1.17407,NaN,1,1.175942,1.170863,1.165903,1.160825
4,GBPUSD:CUR,united kingdom,2021-09-17T14:58:00,currency,1.37484,NaN,2,1.375295,1.367550,1.359943,1.352337
5,NZDUSD:CUR,new zealand,2021-09-17T14:58:00,currency,0.70310,NaN,4,0.705443,0.699896,0.694350,0.688875
6,USDAED:CUR,united arab emirates,2021-09-17T14:52:00,currency,3.67280,NaN,33,3.672800,3.672800,3.672800,3.672800
7,USDAFN:CUR,afghanistan,2021-09-17T14:52:00,currency,85.40000,NaN,112,85.104396,85.628792,86.161646,86.694500
8,USDALL:CUR,albania,2021-09-17T14:52:00,currency,103.00000,NaN,132,103.424790,103.949580,104.484660,105.019740
9,USDAMD:CUR,armenia,2021-09-17T14:26:00,currency,489.00000,NaN,141,494.063325,496.276650,498.539160,500.752485

##### 21 Market forecasts for major commodities
/markets/forecasts/commodity
http://api.tradingeconomics.com/markets/forecasts/commodity?c=guest:guest

In [30]:
te.getMarketsForecasts(category = 'commodity', output_type='df')

,Symbol,Country,Date,Type,Last,Url,Importance,Forecast1,Forecast2,Forecast3,Forecast4
0,BEEF:COM,commodity,2021-09-16T00:00:00,commodity,20.410,NaN,999,20.075850,19.903725,19.731600,19.561500
1,CHE:COM,commodity,2021-09-16T00:00:00,commodity,1.646,NaN,50,1.576245,1.505790,1.438470,1.374120
2,CRYTR:IND,commodity,2021-09-16T00:00:00,commodity,238.016,NaN,999,231.286152,228.334161,225.405599,222.523893
3,DL1:COM,commodity,2021-09-16T00:00:00,commodity,2.207,NaN,149,2.156018,2.106140,2.057586,2.010136
4,GAC:COM,Commodity,2021-09-16T00:00:00,commodity,1925.000,NaN,1000,1900.552500,1876.490000,1852.620000,1829.135000
5,GECNYBGQ:COM,Commodity,2021-09-16T00:00:00,commodity,8650.000,NaN,1000,8619.725000,8589.450000,8559.175000,8529.765000
6,IMR:COM,commodity,2021-09-16T00:00:00,commodity,34.500,NaN,1000,34.213650,33.930750,33.647850,33.368400
7,IUC:COM,Commodity,2021-09-16T00:00:00,commodity,1700.000,NaN,1000,1663.790000,1628.430000,1593.750000,1559.750000
8,LCO1:COM,commodity,2021-09-16T00:00:00,commodity,51500.000,NaN,999,50732.650000,49975.600000,49234.000000,48497.550000
9,LL1:COM,commodity,2021-09-16T00:00:00,commodity,2202.750,NaN,999,2296.407000,2255.015550,2214.559500,2174.571150

##### 22 Market forecasts for major bonds
/markets/forecasts/bond
http://api.tradingeconomics.com/markets/forecasts/bond?c=guest:guest

In [31]:
te.getMarketsForecasts(category = 'bond', output_type='df')

,Symbol,Country,Date,Type,Last,Url,Importance,Forecast1,Forecast2,Forecast3,Forecast4
0,GISR10YR:GOV,israel,2021-09-14T13:27:00,bond,1.055,NaN,999,1.113845,1.155194,1.198047,1.242511
1,GMXN10YR:IND,mexico,2021-09-15T18:37:00,bond,7.003,NaN,999,7.052629,7.148649,7.246061,7.344169
2,BGRGOVB10Y:GOV,bulgaria,2021-09-16T00:00:00,bond,0.300,NaN,999,0.316350,0.333600,0.351780,0.370950
3,CHLGOVBON10Y:GOV,chile,2021-09-16T00:00:00,bond,5.310,NaN,999,5.614609,5.700324,5.787698,5.876178
4,LTUGOVBON10Y:GOV,Lithuania,2021-09-16T00:00:00,bond,0.069,NaN,999,0.037400,0.041140,0.045254,0.049779
5,LVAGOVBON10Y:GOV,latvia,2021-09-16T00:00:00,bond,0.549,NaN,999,0.549000,0.549000,0.549000,0.549000
6,NGAGOVBON10Y:GOV,nigeria,2021-09-16T00:00:00,bond,11.942,NaN,999,12.041708,12.540074,13.059252,13.600401
7,RUGE1M:GOV,Russia,2021-09-16T00:00:00,bond,6.650,NaN,500,6.884460,6.928920,6.974064,7.019892
8,RUGE3M:GOV,Russia,2021-09-16T00:00:00,bond,6.850,NaN,500,7.019487,7.069671,7.119855,7.170039
9,RUGE6M:GOV,Russia,2021-09-16T00:00:00,bond,7.070,NaN,500,7.193336,7.267384,7.342144,7.417616

##### 23 Get major market forecasts by symbol
/markets/forecasts/symbol/{symbols}
http://api.tradingeconomics.com/markets/forecasts/symbol/BULGARIAGOVB10Y:GOV,LITHUANIAGOVBON10Y:GOV,GBGB10YR:GOV?c=guest:guest

In [32]:
te.getMarketsForecasts(symbol = ['psi20:ind', 'indu:ind'], output_type = 'df')

,Symbol,Country,Date,Type,Last,Url,Importance,Forecast1,Forecast2,Forecast3,Forecast4
0,AAPL:US,United States,2021-09-17T15:01:00,stocks,146.73,NaN,500,145.546368,142.373457,139.269716,136.233636
1,DAX:IND,Germany,2021-09-17T15:00:00,index,15472.50,NaN,70,15125.575227,14707.105646,14299.525608,13902.835113
2,INDU:IND,United States,2021-09-17T15:00:00,index,34421.79,NaN,1,33900.998082,33162.814419,32438.493360,31731.500556

## Earnings

##### 24 Default earnings calendar
/earnings
https://api.tradingeconomics.com/earnings?c=guest:guest

In [33]:
te.getEarnings(output_type='df')

,Date,Symbol,Name,Type,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,Session,LastUpdate
0,2021-09-15T00:00:00,JKS:US,JinkoSolar Holding Co. Ltd. ADR,Earnings,5.73,-1.03,None,None,2021/6,United States,None,13,2021-09-17T01:25:00
1,2021-09-15T00:00:00,WUG:GR,Westag&Getalit ST,Earnings,None,None,None,None,2021/6,Germany,None,24,2021-08-27T07:15:00
2,2021-09-15T00:00:00,RDW:LN,Redrow,Earnings,0.17,0.17,None,None,2021/6,United Kingdom,None,9,2021-09-17T01:25:00
3,2021-09-15T00:00:00,VIRC:US,Virco,Earnings,0.24,0.30,None,None,2021/6,United States,None,13,2021-09-15T08:15:00
4,2021-09-15T00:00:00,ROTH:FP,PARIS ORLEANS,Earnings,None,None,None,None,2021/6,France,None,24,2021-09-15T23:32:00
5,2021-09-15T00:00:00,TPE:PW,TAURON Polska Energia,Earnings,None,None,None,None,2021/6,Poland,None,24,2021-09-15T23:31:00
6,2021-09-15T00:00:00,ITX:SM,Inditex,Earnings,0.29,0.29,None,None,2021/6,Spain,EUR,24,2021-09-17T01:24:00
7,2021-09-15T00:00:00,3282:JP,Comforia Res,Earnings,7144.00,7.00,None,None,2021/6,Japan,None,4,2021-09-17T01:24:00
8,2021-09-15T00:00:00,RIPLEY:CI,Ripley Corp,Earnings,-5.09,None,None,None,2021/6,Chile,None,24,2021-09-17T01:24:00
9,2021-09-15T00:00:00,RTN:LN,Restaurant Group,Earnings,-0.05,None,None,None,2021/6,United Kingdom,None,9,2021-09-17T01:25:00

##### 25 Filter earnings calendar by date
/earnings?d1=yyyy-mm-dd
https://api.tradingeconomics.com/earnings?c=guest:guest&d1=2017-01-01

In [36]:
te.getEarnings(initDate='2016-01-01', output_type='df')

,Date,Symbol,Name,Type,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,Session,LastUpdate
0,2016-01-05T00:00:00,LNDC:US,Landec,Earnings,0.07,None,FY2016Q2,Q2/16,2015/9,United States,USD,21,2017-08-03T19:05:00
1,2016-01-05T00:00:00,CMC:US,Commercial Metals,Earnings,0.15,None,FY2016Q3,Q2/16,2015/12,United States,USD,21,2017-08-03T19:05:00
2,2016-01-05T00:00:00,SONC:US,Sonic,Earnings,0.18,None,FY2016Q3,Q3/16,2015/12,United States,USD,21,2017-08-03T21:38:00
3,2016-01-06T00:00:00,MG:US,Mistras,Earnings,0.39,None,FY2016Q2,Q2/16,2015/9,United States,USD,21,2017-08-03T19:05:00
4,2016-01-06T00:00:00,UNF:US,UniFirst,Earnings,1.78,None,FY2016Q1,Q1/16,2015/12,United States,USD,21,2017-08-03T21:38:00
5,2016-01-06T00:00:00,MON:US,Monsanto,Earnings,-0.11,None,FY2016Q1,Q1/16,2016/6,United States,USD,21,2017-08-03T21:38:00
6,2016-01-06T00:00:00,MSM:US,Msc Industrial Direct,Earnings,0.8,None,FY2016Q2,Q1/16,2015/12,United States,USD,21,2017-08-03T19:05:00
7,2016-01-06T00:00:00,RPM:US,Rpm International,Earnings,0.14,None,FY2016Q3,Q2/16,2015/12,United States,USD,21,2017-08-03T19:05:00
8,2016-01-06T00:00:00,RECN:US,Resources Connection,Earnings,0.23,None,FY2016Q2,Q2/16,2015/9,United States,USD,21,2017-08-03T19:05:00
9,2016-01-07T00:00:00,FINL:US,Finish Line,Earnings,-0.07,None,FY2016Q3,Q3/16,2015/9,United States,USD,21,2017-08-03T19:05:00

##### 26 Filter earnings calendar by instrument and date
/earnings/symbol/{symbol}?d1=yyyy-mm-dd
https://api.tradingeconomics.com/earnings/symbol/aapl:us?c=guest:guest&d1=2017-01-01

In [37]:
te.getEarnings(symbols='aapl:us',initDate='2016-01-01', output_type='df')

,Date,Symbol,Name,Type,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,Session,LastUpdate
0,2016-01-26T00:00:00,AAPL:US,Apple,Earnings,3.28,None,FY2016Q1,Q1/16,2015/12,United States,USD,21.0,2017-08-03T21:30:00
1,2016-04-26T00:00:00,AAPL:US,Apple,Earnings,1.9,None,FY2016Q2,Q2/16,2016/3,United States,USD,21.0,2017-08-03T21:02:00
2,2016-07-26T00:00:00,AAPL:US,Apple,Earnings,1.42,None,FY2016Q3,Q3/16,2016/6,United States,USD,21.0,2017-08-03T16:37:00
3,2016-10-25T00:00:00,AAPL:US,Apple,Earnings,1.67,None,FY2016Q4,Q4/16,2016/9,United States,USD,21.0,2017-08-03T15:21:00
4,2017-01-31T00:00:00,AAPL:US,Apple,Earnings,3.36,None,FY2017Q1,Q1/17,2016/12,United States,USD,13.0,2017-08-03T13:42:00
5,2017-05-02T00:00:00,AAPL:US,Apple,Earnings,2.1,None,FY2017Q2,Q2/17,2017/3,United States,USD,13.0,2017-08-03T11:38:00
6,2017-08-01T00:00:00,AAPL:US,Apple,Earnings,1.67,None,FY2017Q3,Q3/17,2017/6,United States,USD,13.0,2017-08-03T09:05:00
7,2017-11-02T00:00:00,AAPL:US,Apple,Earnings,2.07,1.87,FY2017Q4,Q4/17,2017/9,United States,USD,NaN,2017-11-02T22:49:00
8,2018-02-01T00:00:00,AAPL:US,Apple,Earnings,3.89,3.85,FY2018Q1,Q1/18,2017/12,United States,USD,21.0,2018-02-01T21:43:00
9,2018-05-01T00:00:00,AAPL:US,Apple,Earnings,2.73,2.69,FY2018Q2,Q2/18,2018/3,United States,USD,21.0,2018-05-01T20:47:00

##### 27 /earnings/symbol/{symbol}?d1=yyyy-mm-dd&d2=yyyy-mm-dd

https://api.tradingeconomics.com/earnings/symbol/msft:us?c=guest:guest&d1=2016-01-01&d2=2017-12-31

In [38]:
te.getEarnings(symbols = 'msft:us', initDate='2016-01-01', endDate='2017-12-31', output_type='df')

,Date,Symbol,Name,Type,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,Session,LastUpdate
0,2016-01-26T00:00:00,AAPL:US,Apple,Earnings,3.28,None,FY2016Q1,Q1/16,2015/12,United States,USD,21.0,2017-08-03T21:30:00
1,2016-04-26T00:00:00,AAPL:US,Apple,Earnings,1.9,None,FY2016Q2,Q2/16,2016/3,United States,USD,21.0,2017-08-03T21:02:00
2,2016-07-26T00:00:00,AAPL:US,Apple,Earnings,1.42,None,FY2016Q3,Q3/16,2016/6,United States,USD,21.0,2017-08-03T16:37:00
3,2016-10-25T00:00:00,AAPL:US,Apple,Earnings,1.67,None,FY2016Q4,Q4/16,2016/9,United States,USD,21.0,2017-08-03T15:21:00
4,2017-01-31T00:00:00,AAPL:US,Apple,Earnings,3.36,None,FY2017Q1,Q1/17,2016/12,United States,USD,13.0,2017-08-03T13:42:00
5,2017-05-02T00:00:00,AAPL:US,Apple,Earnings,2.1,None,FY2017Q2,Q2/17,2017/3,United States,USD,13.0,2017-08-03T11:38:00
6,2017-08-01T00:00:00,AAPL:US,Apple,Earnings,1.67,None,FY2017Q3,Q3/17,2017/6,United States,USD,13.0,2017-08-03T09:05:00
7,2017-11-02T00:00:00,AAPL:US,Apple,Earnings,2.07,1.87,FY2017Q4,Q4/17,2017/9,United States,USD,NaN,2017-11-02T22:49:00

##### 28 Filter earnings calendar by country
/earnings/country/{country}
https://api.tradingeconomics.com/earnings/country/united%20states?c=guest:guest

In [40]:
te.getEarnings(country = 'united states', output_type='df')

,Date,Symbol,Name,Type,Actual,Forecast,FiscalTag,FiscalReference,CalendarReference,Country,Currency,Session,LastUpdate
0,2021-09-15T00:00:00,IPHA:US,Innate Pharma,Earnings,None,None,None,None,2021/6,United States,None,13,2021-09-15T23:34:00
1,2021-09-15T00:00:00,VIRC:US,Virco,Earnings,0.24,0.30,None,None,2021/6,United States,None,13,2021-09-15T08:15:00
2,2021-09-15T00:00:00,JKS:US,JinkoSolar Holding Co. Ltd. ADR,Earnings,5.73,-1.03,None,None,2021/6,United States,None,13,2021-09-17T01:25:00
3,2021-09-15T00:00:00,AXR:US,Amrep,Earnings,0.22,None,None,None,2021/6,United States,USD,13,2021-09-17T01:27:00
4,2021-09-15T00:00:00,SGMA:US,SigmaTron,Earnings,2.02,None,None,None,2021/6,United States,None,13,2021-09-17T01:28:00
5,2021-09-16T00:00:00,CUSI:US,Cuisine Solutions,Earnings,None,None,None,None,2021/6,United States,None,24,2021-09-15T23:40:00
6,2021-09-16T00:00:00,FONR:US,Fonar,Earnings,None,None,None,None,2021/6,United States,None,24,2021-09-15T23:41:00
7,2021-09-16T00:00:00,PCYG:US,Park City,Earnings,None,0.04,None,None,2021/6,United States,USD,24,2021-09-15T23:41:00
8,2021-09-16T00:00:00,CODA:US,Coda Octopus,Earnings,0.13,0.12,None,None,2021/6,United States,None,13,2021-09-15T08:16:00
9,2021-09-16T00:00:00,IHT:US,InnSuites Hospitality,Earnings,None,None,None,None,2021/6,United States,None,24,2021-09-15T23:42:00

## Financials

##### Financials companies list.
/financials/companies
http://api.tradingeconomics.com/financials/companies?c=guest:guest

In [41]:
te.getFinancialsData(output_type='df')

     Symbol                          Name    Country
0   ARCO:US                 Arcos Dorados  Argentina
1   IRCP:US  Irsa Propiedades Comerciales  Argentina
2    BFR:US            Bbva Banco Frances  Argentina
3    YPF:US                           YPF  Argentina
4    BMA:US                   Banco Macro  Argentina
5  CRESY:US              Cresud Sacif Y A  Argentina
6    EDN:US                        Edenor  Argentina
7   GGAL:US      Grupo Financiero Galicia  Argentina
8   MELI:US                  MERCADOLIBRE  Argentina
9    PAM:US                 Pampa Energia  Argentina

##### 30 Financials companies list filtered by country.
/financials/companies?country={country}
http://api.tradingeconomics.com/financials/companies?country=united%20states&c=guest:guest

In [42]:
te.getFinancialsData(country='united states',output_type='df')

    Symbol                     Name        Country
0     A:US                  Agilent  United States
1    AA:US                    Alcoa  United States
2   AAL:US        American Airlines  United States
3   AAN:US                   Aarons  United States
4  AAOI:US  Applied Optoelectronics  United States
5  AAON:US                     Aaon  United States
6   AAP:US       Advance Auto Parts  United States
7  AAPL:US                    Apple  United States
8   AAT:US          American Assets  United States
9  AAWW:US      Atlas Air Worldwide  United States

##### 31 Financials companies list filtered by more than one country (MAX countries = 5).
/financials/companies?country={countries}
http://api.tradingeconomics.com/financials/companies?country=spain,germany&c=guest:guest

In [46]:
te.getFinancialsData(country=['brazil', 'germany'],output_type='df')

      Symbol                                Name Country
0   ABEV3:BS                               Ambev  Brazil
1    ABEV:US                               Ambev  Brazil
2   ABCB4:BZ                 Banco ABC Brasil SA  Brazil
3   AALR3:BZ          Alliar Medicos A Frente SA  Brazil
4  ALUP11:BZ                       Alupar Invest  Brazil
5   ALSO3:BZ  Aliansce Sonae Shopping Centers SA  Brazil
6   AGRO3:BZ                         Brasil Agro  Brazil
7   AMAR3:BZ                     Marisa Lojas SA  Brazil
8   ARZZ3:BZ     Arezzo Industria  e Comercio SA  Brazil
9   B3SA3:BZ                 Brasil Bolsa Balcao  Brazil

##### 32 Financials data by stock symbol
/financials/symbol/{symbol}
http://api.tradingeconomics.com/financials/symbol/aapl:us?c=guest:guest

In [47]:
te.getFinancialsData(symbol='aapl:us',output_type='df')

,Symbol,Date,last,value1,date1,value2,date2,value3,date3,value4,date4,unit,currency,stock,financialSymbol
0,aapl:us:assets,2021-06-30T00:00:00,329840.000,329840.000,2021-06-30T00:00:00,337158.000,2021-03-31T00:00:00,354054.000,2020-12-31T00:00:00,323888.000,2020-09-30T00:00:00,E+06,$,aapl:us,assets
1,aapl:us:cash-and-equivalent,2021-06-30T00:00:00,19197.000,19197.000,2021-06-30T00:00:00,19022.000,2021-03-31T00:00:00,17281.000,2020-12-31T00:00:00,20243.000,2020-09-30T00:00:00,E+06,$,aapl:us,cash-and-equivalent
2,aapl:us:cost-of-sales,2021-06-30T00:00:00,46179.000,46179.000,2021-06-30T00:00:00,51505.000,2021-03-31T00:00:00,67111.000,2020-12-31T00:00:00,40009.000,2020-09-30T00:00:00,E+06,$,aapl:us,cost-of-sales
3,aapl:us:current-assets,2021-06-30T00:00:00,114423.000,114423.000,2021-06-30T00:00:00,121465.000,2021-03-31T00:00:00,154106.000,2020-12-31T00:00:00,143713.000,2020-09-30T00:00:00,E+06,$,aapl:us,current-assets
4,aapl:us:current-liabilities,2021-06-30T00:00:00,107754.000,107754.000,2021-06-30T00:00:00,106385.000,2021-03-31T00:00:00,132507.000,2020-12-31T00:00:00,105392.000,2020-09-30T00:00:00,E+06,$,aapl:us,current-liabilities
5,aapl:us:debt,2021-06-30T00:00:00,121791.000,121791.000,2021-06-30T00:00:00,121645.000,2021-03-31T00:00:00,112043.000,2020-12-31T00:00:00,113097.000,2020-09-30T00:00:00,E+06,$,aapl:us,debt
6,aapl:us:dy,2021-06-30T00:00:00,0.643,0.643,2021-06-30T00:00:00,0.671,2021-03-31T00:00:00,0.621,2020-12-31T00:00:00,0.753,2020-09-30T00:00:00,None,None,aapl:us,dy
7,aapl:us:ebit,2021-06-30T00:00:00,24126.000,24126.000,2021-06-30T00:00:00,27503.000,2021-03-31T00:00:00,33534.000,2020-12-31T00:00:00,14775.000,2020-09-30T00:00:00,E+06,$,aapl:us,ebit
8,aapl:us:ebitda,2021-06-30T00:00:00,26958.000,26958.000,2021-06-30T00:00:00,30300.000,2021-03-31T00:00:00,36200.000,2020-12-31T00:00:00,17477.000,2020-09-30T00:00:00,E+06,$,aapl:us,ebitda
9,aapl:us:employees,2019-12-31T00:00:00,137000.000,137000.000,2021-06-30T00:00:00,132000.000,2021-03-31T00:00:00,123000.000,2020-12-31T00:00:00,116000.000,2020-09-30T00:00:00,E+00,,aapl:us,employees

##### 33 Financials historical data
/financials/historical/{symbol}
http://api.tradingeconomics.com/financials/historical/aapl:us:assets?c=guest:guest

In [49]:
te.getHistoricalFinancials(symbol='aapl:us', category='assets', output_type='df')

,symbol,category,date,value,reportDate,reference
0,aapl:us,assets ...,2009-12-31T00:00:00,53926.0,2009-12-26T00:00:00,FY2010Q1
1,aapl:us,assets ...,2010-03-31T00:00:00,57057.0,2010-03-27T00:00:00,FY2010Q2
2,aapl:us,assets ...,2010-06-30T00:00:00,64725.0,2010-06-26T00:00:00,FY2010Q3
3,aapl:us,assets ...,2010-09-30T00:00:00,75183.0,2010-09-25T00:00:00,FY2010Q4
4,aapl:us,assets ...,2010-12-31T00:00:00,86742.0,2010-12-25T00:00:00,FY2011Q1
5,aapl:us,assets ...,2011-03-31T00:00:00,94904.0,2011-03-26T00:00:00,FY2011Q2
6,aapl:us,assets ...,2011-06-30T00:00:00,106758.0,2011-06-25T00:00:00,FY2011Q3
7,aapl:us,assets ...,2011-09-30T00:00:00,116371.0,2011-09-24T00:00:00,FY2011Q4
8,aapl:us,assets ...,2011-12-31T00:00:00,138681.0,2011-12-31T00:00:00,FY2012Q1
9,aapl:us,assets ...,2012-03-31T00:00:00,150934.0,2012-03-31T00:00:00,FY2012Q2