In [1]:
import tradingeconomics as te

In [2]:
te.login()

'You are logged in as a guest:guest'

# World Bank

## Indicators and Countries

##### Main categories
/worldBank/categories
https://api.tradingeconomics.com/worldBank/categories?c=guest:guest

In [3]:
te.getWBCategories(output_type='df')

                           category
0                       Agriculture
1   Agriculture & Rural Development
2                 Aid Effectiveness
3                    Climate Change
4                      Demographics
5                       Development
6                  Economy & Growth
7                         Education
8                   Energy & Mining
9                       Environment
10                    External Debt
11                 Financial Sector
12                           Gender
13                           Health
14                   Infrastructure
15                          Poverty
16                   Private Sector
17                    Public Sector
18             Science & Technology
19        Social Protection & Labor
20                            Trade
21                Urban Development

##### Filtering by the main categories
/worldBank/category/{category}
https://api.tradingeconomics.com/worldBank/category/Education?c=guest:guest

In [4]:
te.getWBCategories(category='education',output_type='df')

,category,series_code,series_name,sub_category,sub_category2,sub_category3,title,long_defenition,short_defenition,source,general_comments,aggregation_method,URL,organization,unit,verbose_unit,last_update
0,Education,SE.ADT.1524.LT.FE.ZS,"Literacy rate, youth female (% of females ages...",Education,Gender,None,"Literacy rate, youth female (% of females ages...",NaN,NaN,World Development Indicators,None,Weighted average,/country-list/literacy-rate-youth-female-perce...,UNESCO Institute for Statistics (http://uis.un...,%,%,2020-02-04T00:27:28.593
1,Education,SE.ADT.1524.LT.FM.ZS,"Literacy rate, youth (ages 15-24), gender pari...",Education,Gender,Social Development,Ratio of young literate females to males (% ag...,NaN,NaN,World Development Indicators,None,Weighted average,/country-list/ratio-of-young-literate-females-...,UNESCO Institute for Statistics (http://uis.un...,%,%,2020-02-04T00:27:28.597
2,Education,SE.ADT.1524.LT.MA.ZS,"Literacy rate, youth male (% of males ages 15-24)",Education,Gender,None,"Literacy rate, youth male (% of males ages 15-24)",NaN,NaN,World Development Indicators,None,Weighted average,/country-list/literacy-rate-youth-male-percent...,UNESCO Institute for Statistics (http://uis.un...,%,%,2020-02-04T00:27:28.6
3,Education,SE.ADT.1524.LT.ZS,"Literacy rate, youth total (% of people ages 1...",Education,None,None,"Literacy rate, youth total (% of people ages 1...",NaN,NaN,World Development Indicators,None,Weighted average,/country-list/literacy-rate-youth-total-percen...,UNESCO Institute for Statistics (http://uis.un...,%,%,2020-02-04T00:27:28.603
4,Education,SE.ADT.LITR.MA.ZS,"Literacy rate, adult male (% of males ages 15 ...",Education,Gender,None,"Literacy rate, adult male (% of males ages 15 ...",NaN,NaN,World Development Indicators,None,Weighted average,/country-list/literacy-rate-adult-male-percent...,UNESCO Institute for Statistics (http://uis.un...,%,% of males ages 15 and above,2020-02-04T00:27:28.627
5,Education,SE.ADT.LITR.ZS,"Literacy rate, adult total (% of people ages 1...",Education,None,None,"Literacy rate, adult total (% of people ages 1...",NaN,NaN,World Development Indicators,None,Weighted average,/country-list/literacy-rate-adult-total-percen...,UNESCO Institute for Statistics (http://uis.un...,%,% of people ages 15 and above,2020-02-04T00:27:28.633
6,Education,SE.COM.DURS,"Compulsory education, duration (years)",Education,None,None,Duration of compulsory education (years),NaN,NaN,World Development Indicators,None,None,/country-list/duration-of-compulsory-education...,UNESCO Institute for Statistics (http://uis.un...,Years,years,2020-02-04T00:27:28.637
7,Education,SE.ENR.PRIM.FM.ZS,"School enrollment, primary (gross), gender par...",Education,Gender,Social Development,Ratio of female to male primary enrollment,NaN,NaN,World Development Indicators,None,Weighted average,/country-list/ratio-of-female-to-male-primary-...,UNESCO Institute for Statistics (http://uis.un...,%,%,2020-02-04T00:27:28.647
8,Education,SE.ENR.SECO.FM.ZS,"School enrollment, secondary (gross), gender p...",Education,Gender,Social Development,Ratio of female to male secondary enrollment,NaN,NaN,World Development Indicators,None,Weighted average,/country-list/ratio-of-female-to-male-secondar...,UNESCO Institute for Statistics (http://uis.un...,%,%,2020-02-04T00:27:28.657
9,Education,SE.ENR.TERT.FM.ZS,"School enrollment, tertiary (gross), gender pa...",Education,Gender,Social Development,Ratio of female to male tertiary enrollment,NaN,NaN,World Development Indicators,None,Weighted average,/country-list/ratio-of-female-to-male-tertiary...,UNESCO Institute for Statistics (http://uis.un...,%,%,2020-02-04T00:27:28.663

##### Detailed information about specific indicator for all countries using a series code from the previous method
/worldBank/indicator?c=guest:guest&s={series}
https://api.tradingeconomics.com/worldBank/indicator?c=guest:guest&s=fr.inr.rinr

In [7]:
te.getWBIndicator(series_code = 'SE.ADT.1524.LT.FE.ZS', output_type = 'df')

,symbol,last,date,previous,previousDate,country,category,description,frequency,unit,title,URL,lastUpdate
0,ABW.SE.ADT.1524.LT.FE.ZS,99.39000,2018-06-15T00:00:00,99.36831,2015-06-15T00:00:00,Aruba,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/aruba/literacy-rate-youth-female-percent-of-f...,2021-09-07T15:56:51.76
1,AFG.SE.ADT.1524.LT.FE.ZS,56.25475,2018-06-15T00:00:00,46.10599,2015-06-15T00:00:00,Afghanistan,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/afghanistan/literacy-rate-youth-female-percen...,2021-09-07T15:59:51.8
2,AGO.SE.ADT.1524.LT.FE.ZS,67.28906,2015-06-15T00:00:00,70.58513,2014-06-15T00:00:00,Angola,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/angola/literacy-rate-youth-female-percent-of-...,2021-09-07T16:03:51.467
3,ALB.SE.ADT.1524.LT.FE.ZS,99.63000,2018-06-15T00:00:00,99.08326,2015-06-15T00:00:00,Albania,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/albania/literacy-rate-youth-female-percent-of...,2021-09-07T16:07:51.44
4,AND.SE.ADT.1524.LT.FE.ZS,100.00000,2016-06-15T00:00:00,100.00000,2015-06-15T00:00:00,Andorra,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/andorra/literacy-rate-youth-female-percent-of...,2021-09-07T16:10:51.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,WLD.SE.ADT.1524.LT.FE.ZS,90.53730,2019-06-15T00:00:00,90.27437,2018-06-15T00:00:00,World,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/world/literacy-rate-youth-female-percent-of-f...,2021-09-10T00:03:41.24
136,WSM.SE.ADT.1524.LT.FE.ZS,99.43575,2018-06-15T00:00:00,99.44846,2015-06-15T00:00:00,Samoa,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/samoa/literacy-rate-youth-female-percent-of-f...,2021-09-10T09:37:05.91
137,ZAF.SE.ADT.1524.LT.FE.ZS,96.87589,2017-06-15T00:00:00,99.22904,2015-06-15T00:00:00,South Africa,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/south-africa/literacy-rate-youth-female-perce...,2021-09-10T09:42:05.673
138,ZMB.SE.ADT.1524.LT.FE.ZS,91.62819,2018-06-15T00:00:00,90.62821,2015-06-15T00:00:00,Zambia,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/zambia/literacy-rate-youth-female-percent-of-...,2021-09-10T09:47:05.683
139,ZWE.SE.ADT.1524.LT.FE.ZS,93.50235,2015-06-15T00:00:00,93.18835,2014-06-15T00:00:00,Zimbabwe,Education,"Literacy rate, youth female (% of females ages...",yearly,%,"Literacy rate, youth female (% of females ages...",/zimbabwe/literacy-rate-youth-female-percent-o...,2021-09-10T09:50:05.84

##### List of indicators available for a specific country
/worldBank/country/{country}
https://api.tradingeconomics.com/worldBank/country/portugal?c=guest:guest

In [6]:
te.getWBCountry(country = 'portugal', output_type = 'df')

,symbol,last,date,previous,previousDate,country,category,description,frequency,unit,title,URL,lastUpdate
0,PRT.1.1_ACCESS.ELECTRICITY.TOT,100.00000,2016-06-15T00:00:00,100.00000,2015-06-15T00:00:00,Portugal,Demographics,Access to electricity (% of total population),yearly,%,Access to electricity,/portugal/access-to-electricity-percent-of-tot...,2021-09-09T10:07:15.96
1,PRT.1.1_TOTAL.FINAL.ENERGY.CONSUM,625305.57196,2015-06-15T00:00:00,617562.62964,2014-06-15T00:00:00,Portugal,Energy & Mining,Total final energy consumption (TFEC),yearly,None,Total final energy consumption,/portugal/total-final-energy-consumption-tfec-...,2021-09-09T10:08:48.51
2,PRT.1.2_ACCESS.ELECTRICITY.RURAL,100.00000,2016-06-15T00:00:00,100.00000,2015-06-15T00:00:00,Portugal,Demographics,Access to electricity (% of rural population),yearly,%,Access to electricity (% of rural population),/portugal/access-to-electricity-percent-of-rur...,2021-09-09T10:08:48.51
3,PRT.1.3_ACCESS.ELECTRICITY.URBAN,100.00000,2016-06-15T00:00:00,100.00000,2015-06-15T00:00:00,Portugal,Demographics,Access to electricity (% of urban population),yearly,%,Access to electricity,/portugal/access-to-electricity-percent-of-urb...,2021-09-09T10:08:48.51
4,PRT.2.1_ACCESS.CFT.TOT,100.00000,2016-06-15T00:00:00,100.00000,2015-06-15T00:00:00,Portugal,None,Access to Clean Fuels and Technologies for coo...,yearly,None,Access to Clean Fuels and Technologies for coo...,/portugal/access-to-clean-fuels-and-technologi...,2021-09-09T10:08:48.51
5,PRT.2.1_SHARE.TOTAL.RE.IN.TFEC,27.15730,2015-06-15T00:00:00,30.45701,2014-06-15T00:00:00,Portugal,Energy & Mining,Renewable energy consumption(% in TFEC),yearly,%,Renewable energy consumption,/portugal/renewable-energy-consumptionpercent-...,2021-09-09T10:08:48.51
6,PRT.3.1_RE.CONSUMPTION,169816.10000,2015-06-15T00:00:00,188091.10000,2014-06-15T00:00:00,Portugal,Energy & Mining,Renewable energy consumption (TJ),yearly,TJ,Renewable energy consumption,/portugal/renewable-energy-consumption-tj-wb-d...,2021-09-09T10:08:48.51
7,PRT.4.1.1_TOTAL.ELECTRICITY.OUTPUT,51281.00000,2015-06-15T00:00:00,51959.00000,2014-06-15T00:00:00,Portugal,Energy & Mining,Total electricity output (GWh),yearly,GWh,Total electricity output,/portugal/total-electricity-output-gwh-wb-data...,2021-09-09T17:24:56.473
8,PRT.4.1.2_REN.ELECTRICITY.OUTPUT,24372.00000,2015-06-15T00:00:00,31560.00000,2014-06-15T00:00:00,Portugal,Energy & Mining,Renewable energy electricity output (GWh),yearly,GWh,Renewable energy electricity output,/portugal/renewable-energy-electricity-output-...,2021-09-09T17:24:56.473
9,PRT.4.1_SHARE.RE.IN.ELECTRICITY,47.52637,2015-06-15T00:00:00,60.74020,2014-06-15T00:00:00,Portugal,Energy & Mining,Renewable electricity (% in total electricity ...,yearly,%,Renewable electricity,/portugal/renewable-electricity-percent-in-tot...,2021-09-09T17:24:56.473

##### Detailed information just for a specific indicator and country by using series code or url
/worldBank/indicator?c=guest:guest&s={series_code}
https://api.tradingeconomics.com/worldBank/indicator?c=guest:guest&s=usa.fr.inr.rinr

In [8]:
te.getWBIndicator(series_code = 'usa.fr.inr.rinr', output_type = 'df')

,symbol,last,date,previous,previousDate,country,category,description,frequency,unit,title,URL,lastUpdate
0,USA.FR.INR.RINR,2.30496,2020-06-15T00:00:00,3.43601,2019-06-15T00:00:00,United States,Financial Sector,Real interest rate (%),yearly,%,Real interest rate,/united-states/real-interest-rate-percent-wb-d...,2021-09-09T23:46:41.02

/worldBank/indicator?c=guest:guest&url={url1}
https://api.tradingeconomics.com/worldBank/indicator?c=guest:guest&url=/united-states/real-interest-rate-percent-wb-data.html

In [9]:
te.getWBIndicator( url = '/united-states/real-interest-rate-percent-wb-data.html', output_type = 'df')

,symbol,last,date,previous,previousDate,country,category,description,frequency,unit,title,URL,lastUpdate
0,USA.FR.INR.RINR,2.30496,2020-06-15T00:00:00,3.43601,2019-06-15T00:00:00,United States,Financial Sector,Real interest rate (%),yearly,%,Real interest rate,/united-states/real-interest-rate-percent-wb-d...,2021-09-09T23:46:41.02

##### Historical data for a specific indicator
/worldBank/historical?c=guest:guest&s={series_code}
https://api.tradingeconomics.com/worldBank/historical?c=guest:guest&s=usa.fr.inr.rinr

In [11]:
te.getWBHistorical(series_code = 'usa.fr.inr.rinr', output_type = 'df')

             symbol                 date    value
0   usa.fr.inr.rinr  1961-06-15T00:00:00  3.10788
1   usa.fr.inr.rinr  1962-06-15T00:00:00  3.21535
2   usa.fr.inr.rinr  1963-06-15T00:00:00  3.37488
3   usa.fr.inr.rinr  1964-06-15T00:00:00  2.95167
4   usa.fr.inr.rinr  1965-06-15T00:00:00  2.56591
5   usa.fr.inr.rinr  1966-06-15T00:00:00  2.64942
6   usa.fr.inr.rinr  1967-06-15T00:00:00  2.40623
7   usa.fr.inr.rinr  1968-06-15T00:00:00  1.86391
8   usa.fr.inr.rinr  1969-06-15T00:00:00  2.85177
9   usa.fr.inr.rinr  1970-06-15T00:00:00  2.11994
10  usa.fr.inr.rinr  1971-06-15T00:00:00  0.62262
11  usa.fr.inr.rinr  1972-06-15T00:00:00  0.88722
12  usa.fr.inr.rinr  1973-06-15T00:00:00  2.40973
13  usa.fr.inr.rinr  1974-06-15T00:00:00  1.65107
14  usa.fr.inr.rinr  1975-06-15T00:00:00 -1.28143
15  usa.fr.inr.rinr  1976-06-15T00:00:00  1.26689
16  usa.fr.inr.rinr  1977-06-15T00:00:00  0.57507
17  usa.fr.inr.rinr  1978-06-15T00:00:00  1.88990
18  usa.fr.inr.rinr  1979-06-15T00:00:00  4.03451
19  usa.fr.inr.rinr  1980-06-15T00:00:00  5.71643
20  usa.fr.inr.rinr  1981-06-15T00:00:00  8.59459
21  usa.fr.inr.rinr  1982-06-15T00:00:00  8.17740
22  usa.fr.inr.rinr  1983-06-15T00:00:00  6.61817
23  usa.fr.inr.rinr  1984-06-15T00:00:00  8.14107
24  usa.fr.inr.rinr  1985-06-15T00:00:00  6.56333
25  usa.fr.inr.rinr  1986-06-15T00:00:00  6.19387
26  usa.fr.inr.rinr  1987-06-15T00:00:00  5.59257
27  usa.fr.inr.rinr  1988-06-15T00:00:00  5.59037
28  usa.fr.inr.rinr  1989-06-15T00:00:00  6.69070
29  usa.fr.inr.rinr  1990-06-15T00:00:00  6.03974
30  usa.fr.inr.rinr  1991-06-15T00:00:00  4.91535
31  usa.fr.inr.rinr  1992-06-15T00:00:00  3.88424
32  usa.fr.inr.rinr  1993-06-15T00:00:00  3.54669
33  usa.fr.inr.rinr  1994-06-15T00:00:00  4.89836
34  usa.fr.inr.rinr  1995-06-15T00:00:00  6.59407
35  usa.fr.inr.rinr  1996-06-15T00:00:00  6.32401
36  usa.fr.inr.rinr  1997-06-15T00:00:00  6.60341
37  usa.fr.inr.rinr  1998-06-15T00:00:00  7.14819
38  usa.fr.inr.rinr  1999-06-15T00:00:00  6.45713
39  usa.fr.inr.rinr  2000-06-15T00:00:00  6.84484
40  usa.fr.inr.rinr  2001-06-15T00:00:00  4.62676
41  usa.fr.inr.rinr  2002-06-15T00:00:00  3.04507
42  usa.fr.inr.rinr  2003-06-15T00:00:00  2.22410
43  usa.fr.inr.rinr  2004-06-15T00:00:00  1.60459
44  usa.fr.inr.rinr  2005-06-15T00:00:00  2.98136
45  usa.fr.inr.rinr  2006-06-15T00:00:00  4.78645
46  usa.fr.inr.rinr  2007-06-15T00:00:00  5.22341
47  usa.fr.inr.rinr  2008-06-15T00:00:00  3.08241
48  usa.fr.inr.rinr  2009-06-15T00:00:00  2.46883
49  usa.fr.inr.rinr  2010-06-15T00:00:00  2.06074
50  usa.fr.inr.rinr  2011-06-15T00:00:00  1.13734
51  usa.fr.inr.rinr  2012-06-15T00:00:00  1.30708
52  usa.fr.inr.rinr  2013-06-15T00:00:00  1.46930
53  usa.fr.inr.rinr  2014-06-15T00:00:00  1.37474
54  usa.fr.inr.rinr  2015-06-15T00:00:00  2.28570
55  usa.fr.inr.rinr  2016-06-15T00:00:00  2.43685
56  usa.fr.inr.rinr  2017-06-15T00:00:00  2.17569
57  usa.fr.inr.rinr  2018-06-15T00:00:00  2.44449
58  usa.fr.inr.rinr  2019-06-15T00:00:00  3.43601
59  usa.fr.inr.rinr  2020-06-15T00:00:00  2.30496