In [1]:
import tradingeconomics as te
te.login()

'You are logged in as a guest:guest'

In [6]:
a = te.getCalendarData()   
print(a)

{u'Albania': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183323', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Orthodox Easter Sunday', 'Unit': u'', 'Previous': u''}]}, u'Kosovo': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183322', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Orthodox Easter Sunday', 'Unit': u'', 'Previous': u''}]}, u'Egypt': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183321', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Coptic Easter Sunday', 'Unit': u'', 'Previous': u''}]}, u'Macedonia': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183315', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Orthodox Easter Sunday', 'Unit': u'', 'Previous': u''}]}, u'Ethiopia': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183326', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Easter Sunday', 'Unit': u'', 'Previous': u''}]}, u'Georgia': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183313', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Orthodox Easter Sunday', 'Unit': u'', 'Previous': u''}]}, u'Bosnia and Herzegovina': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183325', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Orthodox Easter Sunday', 'Unit': u'', 'Previous': u''}]}, u'Greece': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183318', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Orthodox Easter Sunday', 'Unit': u'', 'Previous': u''}]}, u'Cyprus': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183316', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Orthodox Easter Sunday', 'Unit': u'', 'Previous': u''}]}, u'Bulgaria': {u'Holidays': [{'Actual': u'', 'Reference': u'', 'Importance': 1L, 'Forecast': u'', 'Source': u'', 'CalendarId': u'183312', 'Date': u'2019-04-08T00:00:00', 'TEForecast': u'', 'Event': u'Orthodox Easter Sunday', 'Unit': u'', 'Previous': u''}]}}

In [7]:
mydata = te.getCalendarData(country = ['japan', 'china'], category = [' Unemployment Rate','Balance of Trade'], initDate = '2017-01-01', endDate = '2018-01-01', output_type= 'df' )
print(mydata)

  CalendarId                 Date        Country                Category  \
0      87213  2016-12-01T13:30:00  United States  Initial Jobless Claims
1      87229  2016-12-08T13:30:00  United States  Initial Jobless Claims
2      87240  2016-12-15T13:30:00  United States  Initial Jobless Claims
3      87249  2016-12-22T13:30:00  United States  Initial Jobless Claims
4      87260  2016-12-29T13:30:00  United States  Initial Jobless Claims
5     144647  2017-01-05T13:30:00  United States  Initial Jobless Claims
6     144663  2017-01-12T13:30:00  United States  Initial Jobless Claims
7     144673  2017-01-19T13:30:00  United States  Initial Jobless Claims
8     144683  2017-01-26T13:30:00  United States  Initial Jobless Claims
9     144694  2017-02-02T13:30:00  United States  Initial Jobless Claims

                    Event Reference Unit                    Source Actual  \
0  Initial Jobless Claims    Nov/26       U.S. Department of Labor   268K
1  Initial Jobless Claims    Dec/03       U.S. Department of Labor   258K
2  Initial Jobless Claims    Dec/10       U.S. Department of Labor   254K
3  Initial Jobless Claims    Dec/17       U.S. Department of Labor   275K
4  Initial Jobless Claims    Dec/24       U.S. Department of Labor   265K
5  Initial Jobless Claims    Dec/31       U.S. Department of Labor   235K
6  Initial Jobless Claims    Jan/07       U.S. Department of Labor   247K
7  Initial Jobless Claims    Jan/14       U.S. Department of Labor   234K
8  Initial Jobless Claims    Jan/21       U.S. Department of Labor   259K
9  Initial Jobless Claims    Jan/28       U.S. Department of Labor   246K

  Previous Forecast TEForecast  Importance
0     251K     253K     253.1K           2
1     268K     258K       263K           2
2     258K     255K       256K           2
3     254K     256K       256K           2
4     275K     264K       271K           2
5     263K     240K       264K           2
6     237K     245K       244K           2
7     249K      240       247K           2
8     237K     247K       247K           2
9     260K     250K       247K           2

In [18]:
import pandas as pd
import numpy as np

df = te.getCalendarData(country = ['japan', 'china'], category = [' Unemployment Rate','Balance of Trade'], initDate = '2017-01-01', endDate = '2018-01-01', output_type= 'df' )

df

,CalendarId,Date,Country,Category,Event,Reference,Unit,Source,Actual,Previous,Forecast,TEForecast,Importance
0,87213,2016-12-01T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Nov/26,,U.S. Department of Labor,268K,251K,253K,253.1K,2
1,87229,2016-12-08T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Dec/03,,U.S. Department of Labor,258K,268K,258K,263K,2
2,87240,2016-12-15T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Dec/10,,U.S. Department of Labor,254K,258K,255K,256K,2
3,87249,2016-12-22T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Dec/17,,U.S. Department of Labor,275K,254K,256K,256K,2
4,87260,2016-12-29T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Dec/24,,U.S. Department of Labor,265K,275K,264K,271K,2
5,144647,2017-01-05T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Dec/31,,U.S. Department of Labor,235K,263K,240K,264K,2
6,144663,2017-01-12T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Jan/07,,U.S. Department of Labor,247K,237K,245K,244K,2
7,144673,2017-01-19T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Jan/14,,U.S. Department of Labor,234K,249K,240,247K,2
8,144683,2017-01-26T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Jan/21,,U.S. Department of Labor,259K,237K,247K,247K,2
9,144694,2017-02-02T13:30:00,United States,Initial Jobless Claims,Initial Jobless Claims,Jan/28,,U.S. Department of Labor,246K,260K,250K,247K,2

In [30]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML

display(HTML(' <span style="color:green"><h1 style="text-align:center">China and Japan Unemployment Rate and Balance of Trade</h1> </span>  '))

df = te.getCalendarData(country = ['japan', 'china'], category = [' Unemployment Rate','Balance of Trade'], initDate = '2017-01-01', endDate = '2018-01-01', output_type= 'df' )
display(HTML(df.to_html()))